"""Reuse the reviewed v1 execution storage mechanics for separate signed-v2 rows.
No existing migration or historical row is modified. Domain guards and separate
ports preserve signed bindings; PostgreSQL generation consumes the SQL output.
"""
from pathlib import Path
import re
root=Path('packages/wos-core/storage')
for backend in ['sqlite','memory']:
 source=(root/backend/'work_contracts.go').read_text()
 source=source.replace('workContractRepository','signedWorkContractRepository').replace('WorkContracts()','SignedWorkContracts()')
 if backend=='sqlite':
  start=source.index('func (r workItemRepository) ContractCandidates')
  tail=source[source.index('func (r signedWorkContractRepository) GetCheckpoint'):]
  source=(source[:start]+tail).replace('\n\t"time"','')
  source=source.replace('work_contract','signed_work_contract').replace('contractState','signedContractState')
  source=source.replace('work_item_id,holder_principal_id,status','work_item_id,credential_id,holder_principal_id,status').replace('VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)','VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').replace('c.WorkItemID.String(), c.HolderPrincipalID','c.WorkItemID.String(), c.SignedBinding.CredentialID.String(), c.HolderPrincipalID')
  source=source.replace('int64(c.Version)','strconv.FormatUint(uint64(c.Version),10)').replace('int64(c.LeaseVersion)','strconv.FormatUint(uint64(c.LeaseVersion),10)').replace('int64(version)','strconv.FormatUint(uint64(version),10)').replace('int64(lease)','strconv.FormatUint(uint64(lease),10)')
  # Keep signed SQL error boundaries retryable without altering v1 storage.
  source=re.sub(r'(rows, err := [^\n]*\.QueryContext[^\n]*\n\tif err != nil \{\n\t\t)return nil, err',r'\1return nil, mapSQLError("query signed state", err)',source)
  source=re.sub(r'(if err (?::=|=) rows.Scan\([^\n]+\); err != nil \{\n\t\t\t)return nil, err',r'\1return nil, mapSQLError("scan signed state", err)',source)
  source=source.replace('return out, rows.Err()', 'return out, mapSQLError("iterate signed state", rows.Err())')

 else:
  start=source.index('type signedWorkContractRepository')
  end=source.index('func (r workItemRepository) ContractCandidates')
  tail=source[source.index('func (r signedWorkContractRepository) GetCheckpoint'):]
  source=source[:source.index('func contractCopy')]+source[start:end]+tail
  source=source.replace('\n\t"encoding/json"','').replace('r.tx.contracts','r.tx.signedContracts').replace('r.tx.checkpoints','r.tx.signedCheckpoints').replace('r.tx.submissions','r.tx.signedSubmissions')
 guard='func (r signedWorkContractRepository) Insert(ctx context.Context, c d.WorkContract) error {'
 assert guard in source
 source=source.replace(guard,guard+'\n if c.SignedBinding==nil {return d.NewError(d.ErrorCodeSignedProtocolRequired,"signed execution binding required")}')
 (root/backend/'signed_work_contracts.go').write_text('// Code generated by tools/signedgen/generate.py; DO NOT EDIT.\n'+source)
