// Code generated by tools/signedgen/generate.py; DO NOT EDIT.
package memory

import (
	"context"
	d "github.com/A1b3rt0M3rcad0/wos/packages/wos-core/domain"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/ports"
	"reflect"
	"sort"
)

type signedWorkContractRepository struct{ tx *transaction }

func (tx *transaction) SignedWorkContracts() ports.WorkContractRepository {
	return signedWorkContractRepository{tx}
}
func (r signedWorkContractRepository) Get(ctx context.Context, scope d.Scope, id d.ID) (d.WorkContract, error) {
	if err := ctx.Err(); err != nil {
		return d.WorkContract{}, err
	}
	if err := r.tx.ensureOpen(); err != nil {
		return d.WorkContract{}, err
	}
	v, ok := r.tx.signedContracts[entityKey(scope, id)]
	if !ok {
		return d.WorkContract{}, d.NewError(d.ErrorCodeNotFound, "contract not found")
	}
	return contractCopy(v), nil
}
func (r signedWorkContractRepository) Current(ctx context.Context, scope d.Scope, work d.ID) (*d.WorkContract, error) {
	list, err := r.List(ctx, scope, ports.ContractFilter{WorkItemID: work, Status: d.ContractActive, Limit: 2})
	if err != nil {
		return nil, err
	}
	if len(list) == 0 {
		return nil, nil
	}
	c, err := r.Get(ctx, scope, list[0].ID)
	return &c, err
}
func (r signedWorkContractRepository) List(ctx context.Context, scope d.Scope, f ports.ContractFilter) ([]d.WorkContract, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if err := r.tx.ensureOpen(); err != nil {
		return nil, err
	}
	if f.Limit < 1 || f.Limit > 101 {
		return nil, d.NewError(d.ErrorCodeInvalidArgument, "contract limit outside 1..101")
	}
	out := []d.WorkContract{}
	for _, v := range r.tx.signedContracts {
		if v.Scope == scope && (f.WorkItemID == "" || f.WorkItemID == v.WorkItemID) && (f.HolderPrincipalID == "" || f.HolderPrincipalID == v.HolderPrincipalID) && (f.Status == "" || f.Status == v.Status) && v.ID > f.After {
			header := v
			header.Spec = d.WorkContractSpec{}
			out = append(out, contractCopy(header))
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	if len(out) > f.Limit {
		out = out[:f.Limit]
	}
	return out, nil
}
func (r signedWorkContractRepository) Insert(ctx context.Context, c d.WorkContract) error {
	if c.SignedBinding == nil {
		return d.NewError(d.ErrorCodeSignedProtocolRequired, "signed execution binding required")
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if err := r.tx.ensureOpen(); err != nil {
		return err
	}
	if err := c.Validate(); err != nil {
		return err
	}
	key := entityKey(c.Scope, c.ID)
	if _, ok := r.tx.signedContracts[key]; ok {
		return d.NewError(d.ErrorCodeAlreadyExists, "contract already exists")
	}
	if _, err := r.tx.WorkItems().Get(ctx, c.Scope, c.WorkItemID); err != nil {
		return err
	}
	old, err := r.Current(ctx, c.Scope, c.WorkItemID)
	if err != nil {
		return err
	}
	if old != nil {
		return d.NewError(d.ErrorCodeWorkAlreadyClaimed, "an open contract exists")
	}
	r.tx.signedContracts[key] = contractCopy(c)
	return nil
}
func (r signedWorkContractRepository) Save(ctx context.Context, c d.WorkContract, version, lease d.Version) error {
	if err := c.Validate(); err != nil {
		return err
	}
	old, err := r.Get(ctx, c.Scope, c.ID)
	if err != nil {
		return err
	}
	if old.Version != version || old.LeaseVersion != lease {
		return d.NewError(d.ErrorCodeVersionConflict, "contract CAS conflict")
	}
	if err := d.ValidateContractUpdate(old, c); err != nil {
		return err
	}
	r.tx.signedContracts[entityKey(c.Scope, c.ID)] = contractCopy(c)
	return nil
}
func (r signedWorkContractRepository) InsertCheckpoint(ctx context.Context, p d.WorkCheckpoint) error {
	if err := p.Validate(); err != nil {
		return err
	}
	c, err := r.Get(ctx, p.Scope, p.ContractID)
	if err != nil {
		return err
	}
	if c.WorkItemID != p.WorkItemID {
		return d.NewError(d.ErrorCodeInvalidScope, "checkpoint task mismatch")
	}
	for _, old := range r.tx.signedCheckpoints {
		if old.Scope == p.Scope && old.ContractID == p.ContractID && old.Sequence == p.Sequence {
			return d.NewError(d.ErrorCodeAlreadyExists, "checkpoint sequence exists")
		}
	}
	key := entityKey(p.Scope, p.ID)
	if old, ok := r.tx.signedCheckpoints[key]; ok {
		if reflect.DeepEqual(old, p) {
			return nil
		}
		return d.NewError(d.ErrorCodeAlreadyExists, "checkpoint immutable")
	}
	r.tx.signedCheckpoints[key] = contractCopy(p)
	return nil
}
func (r signedWorkContractRepository) ListCheckpoints(ctx context.Context, scope d.Scope, contract, after d.ID, limit int) ([]d.WorkCheckpoint, error) {
	if _, err := r.Get(ctx, scope, contract); err != nil {
		return nil, err
	}
	if limit < 1 || limit > 101 {
		return nil, d.NewError(d.ErrorCodeInvalidArgument, "checkpoint limit outside 1..101")
	}
	out := []d.WorkCheckpoint{}
	for _, v := range r.tx.signedCheckpoints {
		if v.Scope == scope && v.ContractID == contract && v.ID > after {
			out = append(out, contractCopy(v))
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	if len(out) > limit {
		out = out[:limit]
	}
	return out, nil
}
func (r signedWorkContractRepository) InsertSubmission(ctx context.Context, p d.WorkSubmission) error {
	if err := p.Validate(); err != nil {
		return err
	}
	c, err := r.Get(ctx, p.Scope, p.Material.ContractID)
	if err != nil {
		return err
	}
	if c.WorkItemID != p.Material.WorkItemID {
		return d.NewError(d.ErrorCodeInvalidScope, "submission task mismatch")
	}
	key := entityKey(p.Scope, p.ID)
	if old, ok := r.tx.signedSubmissions[key]; ok {
		if reflect.DeepEqual(old, p) {
			return nil
		}
		return d.NewError(d.ErrorCodeAlreadyExists, "submission immutable")
	}
	r.tx.signedSubmissions[key] = contractCopy(p)
	return nil
}
func (r signedWorkContractRepository) GetSubmission(ctx context.Context, scope d.Scope, id d.ID) (d.WorkSubmission, error) {
	if err := ctx.Err(); err != nil {
		return d.WorkSubmission{}, err
	}
	if err := r.tx.ensureOpen(); err != nil {
		return d.WorkSubmission{}, err
	}
	v, ok := r.tx.signedSubmissions[entityKey(scope, id)]
	if !ok {
		return d.WorkSubmission{}, d.NewError(d.ErrorCodeNotFound, "submission not found")
	}
	return contractCopy(v), nil
}
func (r signedWorkContractRepository) ListSubmissions(ctx context.Context, scope d.Scope, contract, after d.ID, limit int) ([]d.WorkSubmission, error) {
	if _, err := r.Get(ctx, scope, contract); err != nil {
		return nil, err
	}
	if limit < 1 || limit > 101 {
		return nil, d.NewError(d.ErrorCodeInvalidArgument, "submission limit outside 1..101")
	}
	out := []d.WorkSubmission{}
	for _, v := range r.tx.signedSubmissions {
		if v.Scope == scope && v.Material.ContractID == contract && v.ID > after {
			out = append(out, contractCopy(v))
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	if len(out) > limit {
		out = out[:limit]
	}
	return out, nil
}

func (r signedWorkContractRepository) GetCheckpoint(ctx context.Context, scope d.Scope, id d.ID) (d.WorkCheckpoint, error) {
	if err := ctx.Err(); err != nil {
		return d.WorkCheckpoint{}, err
	}
	if err := r.tx.ensureOpen(); err != nil {
		return d.WorkCheckpoint{}, err
	}
	v, ok := r.tx.signedCheckpoints[entityKey(scope, id)]
	if !ok {
		return d.WorkCheckpoint{}, d.NewError(d.ErrorCodeNotFound, "checkpoint not found")
	}
	return contractCopy(v), nil
}
