"""Generate the PostgreSQL SQL variant of the shared repository implementation.

Domain and Application rules remain shared. Differences are explicit SQL placeholders,
insert-if-absent syntax, search functions and the Outcome row guard. Generated output
is reviewed and committed, so PostgreSQL needs no generator at runtime.
"""
from pathlib import Path
import re
source=Path('packages/wos-core/storage/sqlite')
target=Path('packages/wos-core/storage/postgres')
for name in ['repositories.go','nested.go','relations.go','issues_blockers.go','documentary.go','roadmaps.go','events.go','security.go','queries.go','external_context.go','integration.go','codec.go','migrations.go']:
 s=(source/name).read_text().replace('package sqlite','package postgres',1).replace('sqlite migration','postgres migration')
 def transform_sql(m):
  q=m[1]
  if 'SELECT ' not in q and 'INSERT ' not in q and 'UPDATE ' not in q and 'DELETE ' not in q and 'CREATE ' not in q and 'FROM ' not in q:return m[0]
  if 'INSERT OR IGNORE' in q:q=q.replace('INSERT OR IGNORE','INSERT')+' ON CONFLICT DO NOTHING'
  q=q.replace('instr(lower(title),lower(?))>0','strpos(lower(title),lower(?))>0').replace('instr(lower(description),lower(?))>0','strpos(lower(description),lower(?))>0')
  if re.search(r'SELECT state_revision\s+FROM outcome_coordination',q):q+=' FOR UPDATE'
  counter=0
  def placeholder(_):
   nonlocal counter
   counter+=1;return '$'+str(counter)
  q=re.sub(r'\?',placeholder,q)
  return '`'+q+'`'
 s=re.sub(r'`([^`]*)`',transform_sql,s,flags=re.S)
 if name=='integration.go':
  s=s.replace('ORDER BY next_attempt,id LIMIT 1`','ORDER BY next_attempt,id LIMIT 1 FOR UPDATE SKIP LOCKED`')
 # Query fragments with placeholders need runtime rebinding after composition.
 if name=='queries.go':
  original=(source/name).read_text().replace('package sqlite','package postgres',1)
  s=original.replace('instr(lower(title),lower(?))>0','strpos(lower(title),lower(?))>0').replace('instr(lower(description),lower(?))>0','strpos(lower(description),lower(?))>0').replace('QueryContext(ctx, q, args...)','QueryContext(ctx, rebind(q), args...)')
 # SQL queries composed by fmt.Sprintf, and single-line quoted migration statements.
 s=s.replace('"SELECT id FROM " + table + " WHERE namespace_id = ? AND outcome_id = ? ORDER BY id"','"SELECT id FROM " + table + " WHERE namespace_id = $1 AND outcome_id = $2 ORDER BY id"')
 s=s.replace('encodeTime(c.ExpiresAt), c.Revoked)','encodeTime(c.ExpiresAt), boolInt(c.Revoked))')
 s=s.replace('"SELECT version FROM %s WHERE namespace_id = ? AND outcome_id = ? AND id = ?"','"SELECT version FROM %s WHERE namespace_id = $1 AND outcome_id = $2 AND id = $3"')
 s=s.replace('"SELECT checksum FROM schema_migrations WHERE version = ?"','"SELECT checksum FROM schema_migrations WHERE version = $1"').replace('"INSERT INTO schema_migrations(version, name, checksum, applied_at) VALUES (?, ?, ?, ?)"','"INSERT INTO schema_migrations(version, name, checksum, applied_at) VALUES ($1, $2, $3, $4)"')
 if name=='migrations.go':
  s=s.replace('defer tx.Rollback()', 'defer tx.Rollback()\n if _,err:=tx.ExecContext(ctx,"SELECT pg_advisory_xact_lock(846239010)");err!=nil{return err}',1)
 (target/name).write_text('// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.\n'+s)
for p in (source/'migrations').glob('*.sql'):
 sql=p.read_text()
 # PostgreSQL stores booleans as integer in this shared schema, matching existing
 # relational DTO codecs and preserving all checks. Credential code adapts its bool.
 (target/'migrations'/p.name).write_text(sql)

# Execute the same durability and authorization contracts against a real database.
for name in ['restart_test.go','dependencies_test.go','leases_test.go','documentary_test.go','issues_blockers_test.go','wave10_assessment_test.go','wave10_conclusion_test.go','wave10_immutability_test.go','wave11_roadmap_restart_test.go','security_contract_test.go','external_context_test.go','integration_contract_test.go','continuity_contract_test.go','administrative_override_test.go']:
 s=(source/name).read_text().replace('package sqlite','package postgres',1)
 s=re.sub(r'\bOpen\(', 'openTestPostgres(', s)
 s=re.sub(r'(func Test\w+\(t \*testing.T\) \{)',r'\1\n requirePostgres(t)',s)
 s=re.sub(r'`([^`]*)`',transform_sql,s,flags=re.S)
 (target/name).write_text('// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.\n'+s)
