import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {availableActions,humanActions} from '../../../packages/wos-api/web/assets/actions.js';
import {createIntent,sameScope,reconcileDraft} from '../../../packages/wos-api/web/assets/intents.js';
const inventory=JSON.parse(readFileSync(new URL('../../../packages/wos-api/web/assets/command-exposure.json',import.meta.url)));
const permissions=[...new Set(Object.values(inventory).map(x=>x.permission))];
const context={context:'work_item',entity:{_kind:'work_item',lifecycle:'todo',_operational_state:{display_state:'ready'}},principal:'one',permissions,inventory,protocol:{phase:'legacy'}};
test('explicit human registry agrees with exposure; no signed or admin operation becomes a common action',()=>{for(const name of Object.keys(humanActions)){assert.equal(inventory[name].surface,'human');assert.notEqual(inventory[name].exposure,'S');if(inventory[name].exposure==='A')assert.equal(humanActions[name].advanced,true);}});
test('viewer, missing protocol and signed-v2 cannot acquire a legacy reservation',()=>{for(const overrides of [{permissions:['state:read']},{protocol:null},{protocol:{phase:'signed_contracts_v2'}},{entity:{lifecycle:'todo',contracts_enabled:true}}])assert.ok(!availableActions({...context,...overrides}).some(x=>x.name==='claim_work_item'));assert.ok(availableActions(context).some(x=>x.name==='claim_work_item'));});
test('lifecycle is insufficient to complete another holders work',()=>{for(const principal of ['two',undefined])assert.ok(!availableActions({...context,principal,entity:{lifecycle:'in_progress',current_lease:{principal_id:'one'},_operational_state:{lease_status:'active'}}}).some(x=>x.name==='complete_work_item'));assert.ok(availableActions({...context,entity:{lifecycle:'in_progress',current_lease:{principal_id:'one'},_operational_state:{lease_status:'active'}}}).some(x=>x.name==='complete_work_item'));});
test('draft and revision actions require actual roadmap material',()=>{const base={...context,context:'roadmap',entity:{lifecycle:'draft'}};assert.ok(!availableActions(base).some(x=>x.name==='publish_roadmap_draft'));assert.ok(availableActions({...base,entity:{lifecycle:'draft',draft:{nodes:[]}}}).some(x=>x.name==='publish_roadmap_draft'));});
test('uncertain intent serializes once; edits cannot mutate its payload or scope',()=>{const command={title:'original',nested:{list:['one']}},scope={namespace_id:'ns',outcome_id:'out'};const intent=createIntent('update_outcome',command,scope,'exact-key');command.title='changed';command.nested.list.push('two');scope.outcome_id='other';assert.equal(intent.body,'{"command":{"title":"original","nested":{"list":["one"]}}}');assert.equal(intent.key,'exact-key');assert.ok(sameScope(intent.scope,{namespace_id:'ns',outcome_id:'out'}));assert.ok(!sameScope(intent.scope,scope));assert.ok(Object.isFrozen(intent.scope));});
test('explicit conflict reconciliation preserves local content and changes only observed CAS versions',()=>{const local={title:'my edits',expected_version:1,expected_draft_version:2,nodes:[{title:'local'}]},latest={version:7,draft:{draft_version:9}};const next=reconcileDraft(local,latest);assert.equal(next.title,'my edits');assert.equal(next.expected_version,7);assert.equal(next.expected_draft_version,9);assert.equal(local.expected_version,1);assert.deepEqual(next.nodes,local.nodes);});

test("intent binds an immutable identity independently of mutable form state",()=>{const identity={principal:"first",actor:"human"},intent=createIntent("update_outcome",{}, {},"key",identity);identity.principal="other";assert.equal(intent.identity.principal,"first");assert.ok(Object.isFrozen(intent.identity));});
