// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.
package postgres

import (
	"context"
	"encoding/json"
	"path/filepath"
	"testing"
	"time"

	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/application"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/domain"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/ports"
)

type sqliteAdministrativeAuthorizer struct {
	principal string
}

func (a sqliteAdministrativeAuthorizer) Authorize(_ context.Context, request ports.AuthorizationRequest) error {
	if err := request.Validate(); err != nil {
		return err
	}
	if request.PrincipalID != a.principal {
		return domain.NewError(domain.ErrorCodeForbidden, "principal mismatch")
	}
	switch request.Permission {
	case ports.PermissionWorkAdminCancel, ports.PermissionWorkAdminComplete:
		return nil
	default:
		return domain.NewError(domain.ErrorCodeForbidden, "permission denied")
	}
}

func TestSQLiteAdministrativeCompletionIsDurableAndAudited(t *testing.T) {
	requirePostgres(t)
	ctx := context.Background()
	path := filepath.Join(t.TempDir(), "wos.db")
	store, err := openTestPostgres(path, Options{BusyTimeout: time.Second, MigrateOnOpen: true})
	if err != nil {
		t.Fatal(err)
	}

	claimedAt := time.Date(2026, 10, 3, 5, 0, 0, 0, time.UTC)
	namespaceID := domain.MustParseID("0199eb20-0000-7000-8000-000000000001")
	outcome, work := createSQLiteClaimedWork(t, store, claimedAt, "0199eb21", namespaceID)
	oldLease := *work.CurrentLease

	adminService, err := application.NewServiceWithAuthorizer(
		store,
		sqliteFixedClock{now: claimedAt.Add(time.Minute)},
		&sqliteSequenceIDs{prefix: "0199eb22", next: 1},
		sqliteAdministrativeAuthorizer{principal: "operator"},
	)
	if err != nil {
		t.Fatal(err)
	}
	adminContext := sqliteLeaseCommandContext(
		"operator",
		"0199eb20-0000-7000-8000-000000000102",
	)
	completed, err := adminService.AdministrativeCompleteWorkItem(
		ctx,
		adminContext,
		application.AdministrativeCompleteWorkItemCommand{
			Scope:           outcome.Scope(),
			WorkItemID:      work.ID,
			ExpectedVersion: work.Version,
			ResultSummary:   "operator verified external result",
			Reason:          "original lease owner became unavailable",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if completed.Value.Lifecycle != domain.WorkItemLifecycleDone || completed.Value.CurrentLease != nil {
		t.Fatalf("admin completion state = %#v", completed.Value)
	}
	if oldLease.PrincipalID == adminContext.PrincipalID {
		t.Fatal("test setup did not use a distinct administrative principal")
	}

	if err := store.Close(); err != nil {
		t.Fatal(err)
	}
	reopened, err := openTestPostgres(path, Options{BusyTimeout: time.Second, MigrateOnOpen: true})
	if err != nil {
		t.Fatal(err)
	}
	defer reopened.Close()

	readService, err := application.NewService(
		reopened,
		sqliteFixedClock{now: claimedAt.Add(2 * time.Minute)},
		&sqliteSequenceIDs{prefix: "0199eb23", next: 1},
	)
	if err != nil {
		t.Fatal(err)
	}
	persisted, err := readService.GetWorkItem(ctx, outcome.Scope(), work.ID)
	if err != nil {
		t.Fatal(err)
	}
	if persisted.Value.Lifecycle != domain.WorkItemLifecycleDone || persisted.Value.CurrentLease != nil {
		t.Fatalf("persisted admin completion = %#v", persisted.Value)
	}

	events, err := reopened.SnapshotDomainEvents(ctx, outcome.Scope())
	if err != nil {
		t.Fatal(err)
	}
	var adminEvent *domain.DomainEvent
	for i := range events {
		if events[i].EventType == "work_item.admin_completed" {
			adminEvent = &events[i]
			break
		}
	}
	if adminEvent == nil {
		t.Fatal("administrative completion event was not persisted")
	}
	if adminEvent.PrincipalID != "operator" {
		t.Fatalf("admin event principal = %q, want operator", adminEvent.PrincipalID)
	}
	var payload struct {
		Reason string
	}
	if err := json.Unmarshal(adminEvent.Payload, &payload); err != nil {
		t.Fatal(err)
	}
	if payload.Reason != "original lease owner became unavailable" {
		t.Fatalf("admin event reason = %q", payload.Reason)
	}
}
