// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.
package postgres

import (
	"context"
	"encoding/json"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/application"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/domain"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/ports"
	"path/filepath"
	"testing"
	"time"
)

func TestContinuationFromDiscoverySnapshotAndCursors(t *testing.T) {
	requirePostgres(t)
	ctx := context.Background()
	store := openTestStore(t, filepath.Join(t.TempDir(), "continuity.db"))
	clock := sqliteFixedClock{now: time.Now().UTC()}
	service, err := application.NewService(store, clock, &sqliteSequenceIDs{prefix: "0199d021", next: 1})
	if err != nil {
		t.Fatal(err)
	}
	ns := testID("0199d022-0000-7000-8000-000000000001")
	cc := sqliteCommandContext("0199d023-0000-7000-8000-000000000001", "")
	var outcomes []domain.Outcome
	for i := 0; i < 3; i++ {
		v, err := service.CreateOutcome(ctx, cc, application.CreateOutcomeCommand{NamespaceID: ns, Title: "Continuation", DesiredState: "resume", Priority: domain.PriorityNormal})
		if err != nil {
			t.Fatal(err)
		}
		outcomes = append(outcomes, v.Value)
	}
	seen := map[domain.ID]bool{}
	cursor := ""
	for {
		page, err := service.SearchOutcomes(ctx, ns, ports.OutcomeFilter{Text: "Continuation"}, 1, cursor)
		if err != nil {
			t.Fatal(err)
		}
		for _, v := range page.Items {
			if seen[v.ID] {
				t.Fatal("duplicate discovery item")
			}
			seen[v.ID] = true
		}
		if page.NextCursor == "" {
			break
		}
		cursor = page.NextCursor
	}
	if len(seen) != 3 {
		t.Fatalf("discovered %d outcomes", len(seen))
	}
	if _, err = service.SearchOutcomes(ctx, ns, ports.OutcomeFilter{Text: "different"}, 1, cursor); err == nil {
		t.Fatal("cursor reused with different filter")
	}
	outcome := outcomes[0]
	for i := 0; i < 7; i++ {
		if _, err = service.CreateWorkItem(ctx, cc, application.CreateWorkItemCommand{Scope: outcome.Scope(), Title: "Work", Priority: domain.PriorityNormal}); err != nil {
			t.Fatal(err)
		}
	}
	snap, err := service.GetContinuity(ctx, outcome.Scope(), 2)
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := json.Marshal(snap)
	if len(raw) > application.MaxSnapshotBytes || !snap.Truncated || snap.Counts["work_items"] != 7 || snap.Omitted["work_items"] != 5 {
		t.Fatalf("incorrect bounded snapshot: %+v", snap)
	}
	count := len(snap.Sections["work_items"])
	cursor = snap.SectionCursors["work_items"]
	for cursor != "" {
		page, err := service.GetContinuitySection(ctx, outcome.Scope(), "work_items", 2, cursor)
		if err != nil {
			t.Fatal(err)
		}
		count += len(page.Items)
		cursor = page.NextCursor
	}
	if count != 7 {
		t.Fatalf("continued %d work items", count)
	}
	originalCursor := snap.SectionCursors["work_items"]
	if _, err = service.CreateWorkItem(ctx, cc, application.CreateWorkItemCommand{Scope: outcome.Scope(), Title: "Changed", Priority: domain.PriorityNormal}); err != nil {
		t.Fatal(err)
	}
	if _, err = service.GetContinuitySection(ctx, outcome.Scope(), "work_items", 2, originalCursor); err == nil {
		t.Fatal("mutable cursor silently mixed revisions")
	}
	events := 0
	cursor = ""
	for {
		page, err := service.GetTimeline(ctx, outcome.Scope(), application.TimelineQuery{Limit: 2, Cursor: cursor})
		if err != nil {
			t.Fatal(err)
		}
		events += len(page.Items)
		if page.NextCursor == "" {
			break
		}
		cursor = page.NextCursor
	}
	if events != 9 {
		t.Fatalf("timeline contains %d facts, want 9", events)
	}
	foreign := domain.Scope{NamespaceID: testID("0199d022-0000-7000-8000-000000000002"), OutcomeID: outcome.ID}
	if _, err = service.GetContinuitySection(ctx, foreign, "work_items", 2, originalCursor); err == nil {
		t.Fatal("foreign scope accepted a cursor")
	}
}
func TestWave11UpgradeExistingVersionSevenDatabase(t *testing.T) {
	requirePostgres(t)
	ctx := context.Background()
	store, err := openTestPostgres(filepath.Join(t.TempDir(), "upgrade.db"), Options{})
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	if _, err = store.db.ExecContext(ctx, `CREATE TABLE schema_migrations(version BIGINT PRIMARY KEY,name TEXT NOT NULL,checksum TEXT NOT NULL,applied_at BIGINT NOT NULL)`); err != nil {
		t.Fatal(err)
	}
	migrations, err := loadMigrations()
	if err != nil {
		t.Fatal(err)
	}
	for _, m := range migrations {
		if m.version <= 7 {
			if err = store.applyMigration(ctx, m); err != nil {
				t.Fatal(err)
			}
		}
	}
	service, err := application.NewService(store, sqliteFixedClock{now: time.Now().UTC()}, &sqliteSequenceIDs{prefix: "0199d024", next: 1})
	if err != nil {
		t.Fatal(err)
	}
	cc := sqliteCommandContext("0199d025-0000-7000-8000-000000000001", "")
	created, err := service.CreateOutcome(ctx, cc, application.CreateOutcomeCommand{NamespaceID: testID("0199d025-0000-7000-8000-000000000002"), Title: "Before upgrade", DesiredState: "retained", Priority: domain.PriorityNormal})
	if err != nil {
		t.Fatal(err)
	}
	if err = store.Migrate(ctx); err != nil {
		t.Fatal(err)
	}
	read, err := service.GetOutcome(ctx, created.Value.Scope())
	if err != nil || read.Value.Title != "Before upgrade" {
		t.Fatalf("upgrade lost old data: %v", err)
	}
	if _, err = service.CreateRoadmap(ctx, cc, application.CreateRoadmapCommand{Scope: created.Value.Scope(), PlanScope: domain.RoadmapPlanScope{Kind: domain.RoadmapScopeOutcome, ID: created.Value.ID}, Title: "After upgrade"}); err != nil {
		t.Fatal(err)
	}
}
