// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.
package postgres

import (
	"context"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/application"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/domain"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/ports"
	"path/filepath"
	"testing"
	"time"
)

func TestExternalReferenceDiscoveryIsNamespaceScopedAndDurable(t *testing.T) {
	requirePostgres(t)
	ctx := context.Background()
	path := filepath.Join(t.TempDir(), "external.db")
	store := openTestStore(t, path)
	s, err := application.NewService(store, sqliteFixedClock{now: time.Now().UTC()}, &sqliteSequenceIDs{prefix: "0199d071", next: 1})
	if err != nil {
		t.Fatal(err)
	}
	cc := sqliteCommandContext("0199d072-0000-7000-8000-000000000001", "")
	ns := testID("0199d073-0000-7000-8000-000000000001")
	o, err := s.CreateOutcome(ctx, cc, application.CreateOutcomeCommand{NamespaceID: ns, Title: "External lookup", DesiredState: "Discover without internal outcome ID", Priority: domain.PriorityNormal})
	if err != nil {
		t.Fatal(err)
	}
	ref := domain.ExternalReference{Provider: "woobe", Kind: "project", ExternalID: "project-123", URL: "https://example.test/projects/123"}
	cc.IdempotencyKey = "external-link-00001"
	linked, err := s.LinkExternalReference(ctx, cc, application.LinkExternalReferenceCommand{Scope: o.Value.Scope(), ExpectedVersion: o.Value.Version, Reference: ref})
	if err != nil {
		t.Fatal(err)
	}
	replay, err := s.LinkExternalReference(ctx, cc, application.LinkExternalReferenceCommand{Scope: o.Value.Scope(), ExpectedVersion: o.Value.Version, Reference: ref})
	if err != nil || !replay.IdempotentReplay || replay.Value.Version != linked.Value.Version {
		t.Fatalf("replay %v %+v", err, replay)
	}
	filter := ports.OutcomeFilter{ExternalProvider: ref.Provider, ExternalKind: ref.Kind, ExternalID: ref.ExternalID}
	page, err := s.SearchOutcomes(ctx, ns, filter, 25, "")
	if err != nil || len(page.Items) != 1 {
		t.Fatalf("lookup %v %+v", err, page)
	}
	foreign, err := s.SearchOutcomes(ctx, testID("0199d073-0000-7000-8000-000000000002"), filter, 25, "")
	if err != nil || len(foreign.Items) != 0 {
		t.Fatal("external lookup crossed namespace")
	}
	store.Close()
	store = openTestStore(t, path)
	s, _ = application.NewService(store, sqliteFixedClock{now: time.Now().UTC()}, &sqliteSequenceIDs{prefix: "0199d074", next: 1})
	snapshot, err := s.GetContinuity(ctx, o.Value.Scope(), 1)
	if err != nil || snapshot.Counts["external_references"] != 1 {
		t.Fatalf("missing durable external context: %v %+v", err, snapshot)
	}
}
func TestBrowserSessionRevokedWithParentCredential(t *testing.T) {
	requirePostgres(t)
	ctx := context.Background()
	store := openTestStore(t, filepath.Join(t.TempDir(), "session.db"))
	security := application.SecurityService{Store: store, Clock: sqliteFixedClock{now: time.Now().UTC()}, IDs: &sqliteSequenceIDs{prefix: "0199d075", next: 1}}
	ns := testID("0199d076-0000-7000-8000-000000000001")
	token := "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	if err := security.Bootstrap(ctx, ports.Namespace{ID: ns, Name: "Browser"}, "alice", token); err != nil {
		t.Fatal(err)
	}
	original, err := security.Authenticate(ctx, token)
	if err != nil {
		t.Fatal(err)
	}
	session, sessionToken, err := security.CreateSession(ctx, token)
	if err != nil {
		t.Fatal(err)
	}
	if session.ParentDigest == "" {
		t.Fatal("session lost parent binding")
	}
	if _, _, err = security.CreateSession(ctx, sessionToken); err == nil {
		t.Fatal("session created another session")
	}
	credential, err := store.GetCredential(ctx, original.CredentialDigest)
	if err != nil {
		t.Fatal(err)
	}
	if err = security.RevokeCredential(application.WithIdentity(ctx, original), ns, credential.ID); err != nil {
		t.Fatal(err)
	}
	if _, err = security.Authenticate(ctx, sessionToken); err == nil {
		t.Fatal("session survived source credential revocation")
	}
}
