// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.
package postgres

import (
	"context"
	"encoding/json"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/application"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/domain"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/ports"
	"path/filepath"
	"testing"
	"time"
)

func TestDurableSignalsAtomicRollbackRestartAndDeliveryFencing(t *testing.T) {
	requirePostgres(t)
	ctx := context.Background()
	path := filepath.Join(t.TempDir(), "outbox.db")
	store := openTestStore(t, path)
	now := time.Now().UTC()
	s, _ := application.NewService(store, sqliteFixedClock{now: now}, &sqliteSequenceIDs{prefix: "0199d081", next: 1})
	cc := sqliteCommandContext("0199d082-0000-7000-8000-000000000001", "")
	ns := testID("0199d083-0000-7000-8000-000000000001")
	outcome, err := s.CreateOutcome(ctx, cc, application.CreateOutcomeCommand{NamespaceID: ns, Title: "Durable integration", DesiredState: "Signals survive consumers and restart", Priority: domain.PriorityNormal})
	if err != nil {
		t.Fatal(err)
	}
	endpoint := ports.WebhookEndpoint{ID: testID("0199d084-0000-7000-8000-000000000001"), NamespaceID: ns, URL: "https://example.test/wos", SecretRef: "product-key", KeyID: "key-1"}
	if err = store.InstallEndpoints(ctx, []ports.WebhookEndpoint{endpoint}); err != nil {
		t.Fatal(err)
	}
	trigger, err := s.ConfigureTrigger(ctx, cc, application.ConfigureTriggerCommand{Scope: outcome.Value.Scope(), Name: "Inform consumer", EventTypes: []string{"work_item.created"}, Predicate: domain.EventPredicate{Field: "aggregate.kind", Op: "eq", Value: "work_item"}, TargetEndpointIDs: []domain.ID{endpoint.ID}, SignalType: "product.work_available"})
	if err != nil {
		t.Fatal(err)
	}
	cc.IdempotencyKey = "outbox-work-create-0001"
	command := application.CreateWorkItemCommand{Scope: outcome.Value.Scope(), Title: "Client chooses execution", Priority: domain.PriorityNormal, Lifecycle: domain.WorkItemLifecycleTodo}
	created, err := s.CreateWorkItem(ctx, cc, command)
	if err != nil {
		t.Fatal(err)
	}
	replay, err := s.CreateWorkItem(ctx, cc, command)
	if err != nil || !replay.IdempotentReplay {
		t.Fatal("idempotent source retry failed", err)
	}
	deliveries, err := s.ListDeliveries(ctx, outcome.Value.Scope(), 10, "")
	if err != nil || len(deliveries.Items) != 1 {
		t.Fatalf("outbox duplicate or missing: %v %+v", err, deliveries)
	}
	var firing ports.TriggerFiring
	if err = json.Unmarshal(deliveries.Items[0].Body, &firing); err != nil {
		t.Fatal(err)
	}
	if firing.TriggerID != trigger.Value.ID || firing.Source.Entity.ID != created.Value.ID || firing.SchemaVersion != 1 {
		t.Fatal("incorrect stable integration envelope")
	}
	store.Close()
	store = openTestStore(t, path)
	s, _ = application.NewService(store, sqliteFixedClock{now: now}, &sqliteSequenceIDs{prefix: "0199d085", next: 1})
	deliveries, err = s.ListDeliveries(ctx, outcome.Value.Scope(), 10, "")
	if err != nil || len(deliveries.Items) != 1 || deliveries.Items[0].Status != "pending" {
		t.Fatal("restart lost pending delivery", err)
	}
	leaseA, err := store.ClaimDelivery(ctx, now, testID("0199d086-0000-7000-8000-000000000001"), time.Second)
	if err != nil || leaseA == nil {
		t.Fatal("claim", err)
	}
	leaseB, err := store.ClaimDelivery(ctx, now.Add(2*time.Second), testID("0199d086-0000-7000-8000-000000000002"), time.Minute)
	if err != nil || leaseB == nil || leaseB.FencingToken <= leaseA.FencingToken {
		t.Fatal("reclaim did not fence old worker", err)
	}
	if err = store.FinishDelivery(ctx, *leaseA, now.Add(2*time.Second), "http_200", true, now); err == nil {
		t.Fatal("stale worker acknowledged delivery")
	}
	if err = store.FinishDelivery(ctx, *leaseB, now.Add(2*time.Second), "http_200", true, now); err != nil {
		t.Fatal(err)
	}
	endpoint2 := endpoint
	endpoint2.ID = testID("0199d084-0000-7000-8000-000000000002")
	if err = store.InstallEndpoints(ctx, []ports.WebhookEndpoint{endpoint2}); err != nil {
		t.Fatal(err)
	}
	cc.IdempotencyKey = ""
	if _, err = s.ConfigureTrigger(ctx, cc, application.ConfigureTriggerCommand{Scope: outcome.Value.Scope(), Name: "Failure injection target", EventTypes: []string{"work_item.created"}, TargetEndpointIDs: []domain.ID{endpoint2.ID}, SignalType: "product.work_available"}); err != nil {
		t.Fatal(err)
	}
	// Removing a configured target after validation injects a failure between the
	// source mutation/event and delivery persistence in the same transaction.
	if _, err = store.db.ExecContext(ctx, `DELETE FROM webhook_endpoints WHERE id=$1`, endpoint2.ID.String()); err != nil {
		t.Fatal(err)
	}
	before, err := store.SnapshotDomainEvents(ctx, outcome.Value.Scope())
	if err != nil {
		t.Fatal(err)
	}
	cc.IdempotencyKey = "outbox-failed-create-0001"
	command.Title = "Must roll back"
	if _, err = s.CreateWorkItem(ctx, cc, command); err == nil {
		t.Fatal("expected outbox persistence failure")
	}
	after, _ := store.SnapshotDomainEvents(ctx, outcome.Value.Scope())
	if len(before) != len(after) {
		t.Fatal("failed outbox left source event")
	}
	work, err := s.GetOutcomeState(ctx, outcome.Value.Scope())
	if err != nil || len(work.WorkItems) != 1 {
		t.Fatal("failed outbox left source work", err)
	}
	deliveries, err = s.ListDeliveries(ctx, outcome.Value.Scope(), 10, "")
	if err != nil || len(deliveries.Items) != 1 {
		t.Fatal("failed outbox left partial delivery", err)
	}
	if err = store.InstallEndpoints(ctx, []ports.WebhookEndpoint{endpoint2}); err != nil {
		t.Fatal(err)
	}
	retried, err := s.CreateWorkItem(ctx, cc, command)
	if err != nil || retried.IdempotentReplay {
		t.Fatal("rolled-back idempotency reservation survived", err)
	}
	deliveries, err = s.ListDeliveries(ctx, outcome.Value.Scope(), 10, "")
	if err != nil || len(deliveries.Items) != 3 {
		t.Fatal("retry did not commit both target signals", err)
	}
}
