// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.
package postgres

import (
	"context"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/domain"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/ports"
	"strings"
)

// A fixed switch is the only source of SQL identifiers. Existing per-aggregate
// UNIQUE(namespace_id,outcome_id,id) indexes bound scope and keyset scans. Text
// matching scans scoped metadata, never hydrates aggregate/documentary bodies.
func (r outcomeRepository) SearchReferences(ctx context.Context, scope domain.Scope, f ports.ReferenceFilter) ([]ports.ReferenceCandidate, error) {
	if f.Limit < 1 || f.Limit > 101 {
		return nil, domain.NewError(domain.ErrorCodeInvalidArgument, "invalid reference repository limit")
	}
	branches := []string{}
	args := []any{}
	for _, kind := range f.Kinds {
		var table, title, contextSQL string
		switch kind {
		case "outcome":
			table = "outcomes"
			title = "title"
			contextSQL = `''`
		case "objective":
			table = "objectives"
			title = "title"
			contextSQL = `COALESCE((SELECT substr(o.title,1,128) FROM objectives o WHERE o.namespace_id=t.namespace_id AND o.outcome_id=t.outcome_id AND o.id=t.parent_objective_id), '')`
		case "work_item":
			table = "work_items"
			title = "title"
			contextSQL = `COALESCE((SELECT substr(o.title,1,128) FROM objectives o WHERE o.namespace_id=t.namespace_id AND o.outcome_id=t.outcome_id AND o.id=t.objective_id), '')`
		case "issue":
			table = "issues"
			title = "title"
			contextSQL = `''`
		case "blocker":
			table = "blockers"
			title = "description"
			contextSQL = `''`
		case "artifact":
			table = "artifacts"
			title = "name"
			contextSQL = `''`
		case "evidence":
			table = "evidence"
			title = "description"
			contextSQL = `''`
		case "decision":
			table = "decisions"
			title = "title"
			contextSQL = `''`
		case "roadmap":
			table = "roadmaps"
			title = "title"
			contextSQL = `''`
		case "relation":
			table = "relations"
			title = "relation_type"
			contextSQL = `''`
		case "evidence_link":
			table = "evidence_links"
			title = "rationale"
			contextSQL = `''`
		default:
			return nil, domain.NewError(domain.ErrorCodeInvalidArgument, "invalid reference kind")
		}
		q := "SELECT t.id,t.version,'" + string(kind) + "' AS kind,substr(t." + title + ",1,128) AS title,t.lifecycle," + contextSQL + " AS display_context FROM " + table + " t WHERE t.namespace_id=? AND t.outcome_id=?"
		args = append(args, scope.NamespaceID.String(), scope.OutcomeID.String())
		if !f.ID.IsZero() {
			q += " AND t.id=?"
			args = append(args, f.ID.String())
		}
		if f.Query != "" {
			q += " AND strpos(translate(t." + title + ",'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),translate(?,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'))>0"
			args = append(args, f.Query)
		}
		if f.Priority != "" {
			if kind != domain.EntityKindWorkItem {
				return nil, domain.NewError(domain.ErrorCodeInvalidArgument, "priority requires Task kind")
			}
			q += " AND t.priority=?"
			args = append(args, string(f.Priority))
		}
		if f.Lifecycle != "" {
			q += " AND t.lifecycle=?"
			args = append(args, f.Lifecycle)
		}
		if !f.AfterID.IsZero() {
			if kind < f.AfterKind {
				q += " AND 1=0"
			} else if kind == f.AfterKind {
				q += " AND t.id>?"
				args = append(args, f.AfterID.String())
			}
		}
		branches = append(branches, q)
	}
	if len(branches) == 0 {
		return []ports.ReferenceCandidate{}, nil
	}
	q := "SELECT id,version,kind,title,lifecycle,display_context FROM (" + strings.Join(branches, " UNION ALL ") + ") candidates ORDER BY kind,id LIMIT ?"
	args = append(args, f.Limit)
	rows, err := r.uow.tx.QueryContext(ctx, rebind(q), args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := []ports.ReferenceCandidate{}
	for rows.Next() {
		var item ports.ReferenceCandidate
		var id, kind string
		if err = rows.Scan(&id, &item.Version, &kind, &item.Title, &item.Lifecycle, &item.DisplayContext); err != nil {
			return nil, err
		}
		parsed, e := domain.ParseID(id)
		if e != nil {
			return nil, e
		}
		item.Ref = domain.EntityRef{Scope: scope, Kind: domain.EntityKind(kind), ID: parsed}
		result = append(result, item)
	}
	return result, rows.Err()
}
