// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.
package postgres

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	a "github.com/A1b3rt0M3rcad0/wos/packages/wos-core/application"
	d "github.com/A1b3rt0M3rcad0/wos/packages/wos-core/domain"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/ports"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/signing"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/storage/memory"
	"path/filepath"
	"reflect"
	"testing"
	"time"
)

func TestSignedReviewStorageDeliveryPrecisionImmutableFactsAndRestore(t *testing.T) {
	requirePostgres(t)
	for _, backend := range []string{"memory", "sql"} {
		t.Run(backend, func(t *testing.T) {
			ctx := context.Background()
			now := time.Now().UTC()
			path := filepath.Join(t.TempDir(), "signed-review.db")
			var store interface {
				ports.SecurityStore
				ports.TransactionManager
			}
			var sqlStore *Store
			if backend == "memory" {
				store = memory.New()
			} else {
				sqlStore = openTestStore(t, path)
				store = sqlStore
			}
			must := func(err error) {
				t.Helper()
				if err != nil {
					t.Fatal(err)
				}
			}
			ns := testID("0199a333-0000-7000-8000-000000000001")
			scope := d.Scope{NamespaceID: ns, OutcomeID: testID("0199a333-0000-7000-8000-000000000002")}
			sec := a.SecurityService{Store: store, Clock: sqliteFixedClock{now}, IDs: &sqliteSequenceIDs{prefix: "0199a334", next: 1}}
			must(sec.Bootstrap(ctx, ports.Namespace{ID: ns, Name: "signed-storage"}, "issuer", "signed-storage-bootstrap-at-least-32-characters"))
			outcome, err := d.NewOutcome(scope.OutcomeID, ns, "Signed storage", "", "Verified", d.PriorityNormal, now)
			must(err)
			outcome.Lifecycle = d.OutcomeLifecycleActive
			work, err := d.NewWorkItem(testID("0199a333-0000-7000-8000-000000000003"), scope, "Deliver then review", "", d.PriorityNormal, d.WorkItemLifecycleTodo, now)
			must(err)
			work.ContractsEnabled = true
			pub, private, err := ed25519.GenerateKey(rand.Reader)
			must(err)
			fp, err := signing.Fingerprint(pub)
			must(err)
			keyID := testID("0199a333-0000-7000-8000-000000000004")
			binding := d.SignedContractBinding{ProtocolVersion: 2, ServerID: "persisted-server", CredentialID: testID("0199a333-0000-7000-8000-000000000005"), SignerKeyID: keyID, AcceptanceFloor: d.AcceptanceIndependentReview, PolicyRevision: 1, AllowedSigningKeyIDs: []d.ID{keyID}}
			contract, err := d.NewWorkContract(testID("0199a333-0000-7000-8000-000000000006"), testID("0199a333-0000-7000-8000-000000000007"), work, "executor", d.ActorRef{Kind: d.ActorKindAgent, Provider: "test", ID: "executor"}, d.DefaultContractLeasePolicy(), 30, d.WorkContractSpec{Title: work.Title}, 0, now)
			must(err)
			contract.SignedBinding = &binding
			// New v2 storage keeps counters above signed/JavaScript integer limits exact.
			contract.Version = d.Version(uint64(1)<<63) + 7
			contract.LeaseVersion = d.Version(uint64(1)<<63) + 9
			must(work.BindContract(contract, now))
			uow, err := store.Begin(ctx)
			must(err)
			signed := uow.(ports.SignedContractUnitOfWork)
			must(uow.Outcomes().Insert(ctx, outcome))
			must(uow.WorkItems().Insert(ctx, work))
			must(signed.SignedWorkContracts().Insert(ctx, contract))
			issuerKey := d.SigningKey{ID: keyID, NamespaceID: ns, PrincipalID: "issuer", Purpose: "issuer", Algorithm: "Ed25519", PublicKey: base64.StdEncoding.EncodeToString(pub), Fingerprint: fp, Version: 1, Status: "active", CreatedAt: now, UpdatedAt: now}
			must(uow.(ports.SigningIdentityUnitOfWork).SigningIdentity().SaveKey(ctx, issuerKey, 0))
			payload := signing.SpecPayload[d.WorkContractSpec]{Binding: signing.Binding{ProtocolVersion: 2, ServerID: binding.ServerID, NamespaceID: ns.String(), OutcomeID: scope.OutcomeID.String(), PrincipalID: "executor", SignerKeyID: keyID.String()}, ContractKind: "execution", ContractID: contract.ID.String(), WorkItemID: work.ID.String(), Spec: contract.Spec}
			envelope, err := signing.Sign(signing.ContractSpec, payload, keyID.String(), private)
			must(err)
			doc, err := signing.ToDocument(envelope)
			must(err)
			proof, err := json.Marshal(doc.Proof)
			must(err)
			fact := d.SignedFact{ID: testID("0199a333-0000-7000-8000-000000000008"), Scope: scope, ContractID: contract.ID, ContractKind: "execution", Kind: "specification", PrincipalID: "executor", KeyID: keyID, Payload: doc.Payload, PayloadDigest: signing.Digest(doc.Payload), Proof: proof, RecordedAt: now}
			must(signed.SignedContracts().InsertFact(ctx, fact))
			must(uow.Commit())
			// A rejected or rolled-back return leaves no delivered authority or review.
			uow, err = store.Begin(ctx)
			must(err)
			signed = uow.(ports.SignedContractUnitOfWork)
			stored, err := signed.SignedWorkContracts().Get(ctx, scope, contract.ID)
			must(err)
			if stored.Version != contract.Version || stored.LeaseVersion != contract.LeaseVersion {
				t.Fatal("counter precision lost")
			}
			material := d.NormalizeResultMaterial(d.WorkResultMaterial{ContractID: contract.ID, WorkItemID: work.ID, SpecDigest: contract.SpecDigest, Summary: "exact immutable submission"})
			digest, err := d.SemanticDigest(material)
			must(err)
			submission := d.WorkSubmission{ID: testID("0199a333-0000-7000-8000-000000000009"), Scope: scope, Material: material, Digest: digest, PrincipalID: "executor", Actor: contract.Actor, SubmittedAt: now}
			must(signed.SignedWorkContracts().InsertSubmission(ctx, submission))
			oldVersion := stored.Version
			must(stored.Deliver(submission, "executor", stored.ExecutionID, stored.FencingToken, stored.Version, now))
			must(signed.SignedWorkContracts().Save(ctx, stored, oldVersion, stored.LeaseVersion))
			must(uow.Rollback())
			uow, err = store.Begin(ctx)
			must(err)
			signed = uow.(ports.SignedContractUnitOfWork)
			stored, err = signed.SignedWorkContracts().Get(ctx, scope, contract.ID)
			must(err)
			if stored.Status != d.ContractActive {
				t.Fatal("rollback left delivered execution")
			}
			must(signed.SignedWorkContracts().InsertSubmission(ctx, submission))
			oldVersion = stored.Version
			must(stored.Deliver(submission, "executor", stored.ExecutionID, stored.FencingToken, stored.Version, now))
			must(signed.SignedWorkContracts().Save(ctx, stored, oldVersion, stored.LeaseVersion))
			review := d.ReviewCase{ID: testID("0199a333-0000-7000-8000-000000000010"), Scope: scope, WorkItemID: work.ID, WorkContractID: contract.ID, SubmissionID: submission.ID, SubmissionDigest: submission.Digest, IssuedSpecDigest: fact.PayloadDigest, PolicyRevision: 1, AcceptanceFloor: d.AcceptanceIndependentReview, Round: 1, Version: 1, Status: d.ReviewPending, ExecutionPrincipals: []string{"executor"}, CreatedAt: now, UpdatedAt: now}
			must(signed.SignedContracts().InsertCase(ctx, review))
			must(uow.Commit())
			service, err := a.NewService(store, sqliteFixedClock{now}, &sqliteSequenceIDs{prefix: "0199a335", next: 1})
			must(err)
			cc := d.CommandContext{PrincipalID: "executor", Actor: contract.Actor, CommandID: testID("0199a333-0000-7000-8000-000000000015"), IdempotencyKey: "signed-obligation-mutation-1"}
			changedTitle := "rewrite frozen task"
			_, err = service.UpdateWorkItem(ctx, cc, a.UpdateWorkItemCommand{Scope: scope, WorkItemID: work.ID, ExpectedVersion: work.Version, Title: &changedTitle})
			if code, _ := d.ErrorCodeOf(err); code != d.ErrorCodeSignedProtocolRequired {
				t.Fatalf("embedded unsigned task edit bypass: %v", err)
			}
			cc.CommandID = testID("0199a333-0000-7000-8000-000000000016")
			cc.IdempotencyKey = "unsigned-review-assessment-1"
			_, err = service.RecordCriterionAssessment(ctx, cc, a.RecordCriterionAssessmentCommand{Owner: work.Ref(), CriterionID: testID("0199a333-0000-7000-8000-000000000017"), CriterionRevision: 1, ExpectedVersion: work.Version, Result: d.AssessmentResultMet, Rationale: "unsigned"})
			if code, _ := d.ErrorCodeOf(err); code != d.ErrorCodeSignedProtocolRequired {
				t.Fatalf("embedded unsigned assessment bypass: %v", err)
			}
			cc.CommandID = testID("0199a333-0000-7000-8000-000000000018")
			cc.IdempotencyKey = "unsigned-parent-completion-1"
			_, err = service.AchieveOutcome(ctx, cc, a.AchieveOutcomeCommand{Scope: scope, ExpectedVersion: outcome.Version, Reason: "unsigned parent bypass"})
			if code, _ := d.ErrorCodeOf(err); code != d.ErrorCodeSignedProtocolRequired {
				t.Fatalf("parent completion bypass: %v", err)
			}

			uow, err = store.Begin(ctx)
			must(err)
			signed = uow.(ports.SignedContractUnitOfWork)
			current, err := signed.SignedContracts().OpenCase(ctx, scope, work.ID)
			must(err)
			if current == nil || current.SubmissionID != submission.ID {
				t.Fatal("immutable review target missing")
			}
			duplicate := review
			duplicate.ID = testID("0199a333-0000-7000-8000-000000000099")
			if err = signed.SignedContracts().InsertCase(ctx, duplicate); err == nil {
				t.Fatal("two open reviews for same Task")
			}
			must(uow.Rollback())
			uow, err = store.Begin(ctx)
			must(err)
			signed = uow.(ports.SignedContractUnitOfWork)
			reviewer, err := d.NewReviewContract(testID("0199a333-0000-7000-8000-000000000011"), testID("0199a333-0000-7000-8000-000000000012"), review, "reviewer", d.ActorRef{Kind: d.ActorKindAgent, Provider: "test", ID: "reviewer"}, "", binding, d.DefaultContractLeasePolicy(), 30, now)
			must(err)
			must(signed.SignedContracts().InsertReviewContract(ctx, reviewer))
			oldCase := review.Version
			must(review.Bind(reviewer, now))
			must(signed.SignedContracts().SaveCase(ctx, review, oldCase))
			must(uow.Commit())
			if sqlStore != nil {
				sqlStore = reopenIntegrationFixture(t, sqlStore, path)
				store = sqlStore
			}
			uow, err = store.Begin(ctx)
			must(err)
			signed = uow.(ports.SignedContractUnitOfWork)
			restored, err := signed.SignedContracts().Case(ctx, scope, review.ID)
			must(err)
			if !reflect.DeepEqual(restored, review) {
				t.Fatal("review state changed on restart/restore")
			}
			gotFact, err := signed.SignedContracts().Fact(ctx, scope, fact.ID)
			must(err)
			if !reflect.DeepEqual(gotFact, fact) {
				t.Fatal("canonical signed fact changed on restore")
			}
			restoredProof := signing.Proof{}
			must(json.Unmarshal(gotFact.Proof, &restoredProof))
			restoredEnvelope, err := (signing.Document{Payload: gotFact.Payload, Proof: restoredProof}).Envelope()
			must(err)
			if _, err = signing.Verify(restoredEnvelope, signing.ContractSpec, keyID.String(), pub); err != nil {
				t.Fatal("restored fact no longer verifies", err)
			}
			counts, err := signed.SignedContracts().Counts(ctx, ns, "reviewer", binding.CredentialID, now)
			must(err)
			if counts.NamespaceWork != 0 || counts.PrincipalReview != 1 || counts.CredentialReview != 1 {
				t.Fatalf("active quotas count wrong authority: %+v", counts)
			}
			reviewer, err = signed.SignedContracts().ReviewContract(ctx, scope, reviewer.ID)
			must(err)
			v, l := reviewer.Version, reviewer.LeaseVersion
			must(reviewer.Close(d.ContractCompleted, "reviewer", "inconclusive", v, now))
			must(signed.SignedContracts().SaveReviewContract(ctx, reviewer, v, l))
			oldCase = restored.Version
			must(restored.Release(reviewer, now))
			must(signed.SignedContracts().SaveCase(ctx, restored, oldCase))
			must(uow.Commit())
		})
	}
}
