// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.
package postgres

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	a "github.com/A1b3rt0M3rcad0/wos/packages/wos-core/application"
	d "github.com/A1b3rt0M3rcad0/wos/packages/wos-core/domain"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/ports"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/signing"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/storage/memory"
	"path/filepath"
	"testing"
	"time"
)

func TestSignedReviewCorrectionJourneyWithoutExecutorAuthority(t *testing.T) {
	requirePostgres(t)
	for _, backend := range []string{"memory", "sql"} {
		t.Run(backend, func(t *testing.T) {
			floor := d.AcceptanceIndependentReview
			hasCriteria := true
			var store interface {
				ports.SecurityStore
				ports.TransactionManager
			}
			if backend == "memory" {
				store = memory.New()
			} else {
				store = openTestStore(t, filepath.Join(t.TempDir(), "signed-acquisition.db"))
			}
			ctx := context.Background()
			now := time.Now().UTC()
			clock := sqliteFixedClock{now}
			ids := &sqliteSequenceIDs{prefix: "0199a556", next: 1}
			sec := a.SecurityService{Store: store, Clock: clock, IDs: ids}
			must := func(err error) {
				t.Helper()
				if err != nil {
					t.Fatal(err)
				}
			}
			ns := testID("0199a555-0000-7000-8000-000000000001")
			scope := d.Scope{NamespaceID: ns, OutcomeID: testID("0199a555-0000-7000-8000-000000000002")}
			must(sec.Bootstrap(ctx, ports.Namespace{ID: ns, Name: "signed-acquisition"}, "admin", "signed-acquisition-bootstrap-token-at-least-32"))
			admin, err := sec.Authenticate(ctx, "signed-acquisition-bootstrap-token-at-least-32")
			must(err)
			adminCtx := a.WithIdentity(ctx, admin)
			must(sec.SetGrant(adminCtx, ports.NamespaceGrant{NamespaceID: ns, PrincipalID: "executor", Permissions: []ports.Permission{ports.PermissionStateRead, ports.PermissionWorkContractAcquire, ports.PermissionWorkWrite, ports.PermissionWorkContractReturn, ports.PermissionWorkCompleteDirect, ports.PermissionAssessmentWrite, ports.PermissionConclusionWrite, ports.PermissionRecordsWrite}}))
			credential, token, err := sec.IssueCredential(adminCtx, ns, "executor", d.ActorRef{Kind: d.ActorKindAgent, Provider: "test", ID: "executor"}, now.Add(time.Hour))
			must(err)
			identity, err := sec.Authenticate(ctx, token)
			must(err)
			agentCtx := a.WithIdentity(ctx, identity)
			pub, private, err := ed25519.GenerateKey(rand.Reader)
			must(err)
			fp, err := signing.Fingerprint(pub)
			must(err)
			server := d.ServerIdentity{ID: testID("0199a555-0000-7000-8000-000000000003"), IssuerKeyID: testID("0199a555-0000-7000-8000-000000000004"), PublicKey: base64.StdEncoding.EncodeToString(pub), Fingerprint: fp, CreatedAt: now}
			service, err := a.NewService(store, clock, ids)
			must(err)
			must(service.ConfigureSignedIssuer(ctx, acquisitionIssuer{server, private}, d.AcceptanceDirect))
			agentPub, agentPrivate, err := ed25519.GenerateKey(rand.Reader)
			must(err)
			agentFP, err := signing.Fingerprint(agentPub)
			must(err)
			agentKey := testID("0199a555-0000-7000-8000-000000000005")
			uow, err := store.Begin(ctx)
			must(err)
			registry := uow.(ports.SigningIdentityUnitOfWork).SigningIdentity()
			must(registry.SaveKey(ctx, d.SigningKey{ID: agentKey, NamespaceID: ns, PrincipalID: "executor", Purpose: "agent", Algorithm: "Ed25519", PublicKey: base64.StdEncoding.EncodeToString(agentPub), Fingerprint: agentFP, Version: 1, Status: "active", CreatedAt: now, UpdatedAt: now}, 0))
			policy := d.CredentialPolicy{NamespaceID: ns, CredentialID: credential.ID, PrincipalID: "executor", Version: 1, PermittedOperations: []string{string(ports.PermissionStateRead), string(ports.PermissionWorkContractAcquire), string(ports.PermissionWorkWrite), string(ports.PermissionWorkContractReturn), string(ports.PermissionWorkCompleteDirect), string(ports.PermissionAssessmentWrite), string(ports.PermissionConclusionWrite), string(ports.PermissionRecordsWrite)}, AcceptanceFloor: floor, AllowedSigningKeyIDs: []d.ID{agentKey}, MaxActiveWorkContracts: 10, MaxActiveReviewContracts: 1, UpdatedAt: now}
			must(registry.SaveCredentialPolicy(ctx, policy, 0))
			outcome, err := d.NewOutcome(scope.OutcomeID, ns, "signed workload", "", "verified", d.PriorityNormal, now)
			must(err)
			outcome.Lifecycle = d.OutcomeLifecycleActive
			must(uow.Outcomes().Insert(ctx, outcome))
			works := []d.WorkItem{}
			for i := 0; i < 4; i++ {
				w, e := d.NewWorkItem(testID(fmt.Sprintf("0199a555-0000-7000-8000-%012x", 20+i)), scope, "precise signed task", "", d.PriorityNormal, d.WorkItemLifecycleTodo, now)
				must(e)
				w.ContractsEnabled = true
				criterion, e := d.NewSuccessCriterion(testID(fmt.Sprintf("0199a555-0000-7000-8000-%012x", 100+i)), w.Ref(), "verified result", "", true, d.VerificationModeEvidenceReview)
				must(e)
				if hasCriteria {
					must(w.Criteria.Add(criterion))
				}
				must(uow.WorkItems().Insert(ctx, w))
				works = append(works, w)
			}
			protocol := uow.(ports.WorkProtocolUnitOfWork).WorkProtocol()
			state, err := protocol.Lock(ctx, ns, true)
			must(err)
			state.Phase = d.WorkProtocolSigned
			state.WriterEpoch = 2
			state.WritersDrained = true
			state.Version++
			state.UpdatedAt = now
			state.UpdatedBy = "operator"
			state.Reason = "test-only operator activation; public cutover remains separately gated"
			must(protocol.Save(ctx, state, 1))
			must(uow.Commit())

			w := works[0]
			cid, e := ids.NewID()
			must(e)
			cc := d.CommandContext{PrincipalID: identity.PrincipalID, Actor: identity.Actor, CommandID: cid, IdempotencyKey: "atomic-return-acquisition"}
			acquired, e := service.AcquireSignedWorkContract(agentCtx, cc, a.AcquireSignedWorkContractCommand{Scope: scope, WorkItemID: w.ID, ExpectedWorkItemVersion: w.Version, SignerKeyID: agentKey, TTLSeconds: 300})
			must(e)
			c := acquired.Value.Contract
			work := acquired.Value.WorkItem
			rid, e := ids.NewID()
			must(e)
			request := signing.WorkReturnPayload[a.SignedReturnMaterial]{RequestBinding: signing.RequestBinding{Binding: signing.Binding{ProtocolVersion: 2, ServerID: server.ID.String(), NamespaceID: ns.String(), OutcomeID: scope.OutcomeID.String(), PrincipalID: identity.PrincipalID, SignerKeyID: agentKey.String()}, OperationKind: "work_return", RequestID: rid.String(), IdempotencyKey: "atomic-signed-return", ContractID: c.ID.String(), WorkItemID: work.ID.String(), ExecutionID: c.ExecutionID.String(), FencingToken: signing.Decimal(c.FencingToken), SpecDigest: c.SignedBinding.SpecificationDigest, AuthorityDigest: signing.Digest(acquired.Value.IssuedAuthority.Payload), ExpectedContractVersion: signing.Decimal(c.Version), ExpectedLeaseVersion: signing.Decimal(c.LeaseVersion), ExpectedWorkItemVersion: signing.Decimal(work.Version), PolicyRevision: signing.Decimal(policy.Version)}, CompletionIntent: "auto", Material: a.SignedReturnMaterial{Result: d.NewSignedResultMaterial(d.WorkResultMaterial{ContractID: c.ID, WorkItemID: work.ID, SpecDigest: c.SignedBinding.SpecificationDigest, Summary: "bounded implementation verified"}), Reason: "verified direct result"}}
			criterion := d.SuccessCriterion{}
			if hasCriteria {
				criterion = work.Criteria.Items[0]
			}
			request.Material.Artifacts = []a.SyncArtifactInput{{LocalKey: "build", Artifact: a.RegisterArtifactCommand{Scope: scope, ArtifactType: "source", Name: "tested commit", URI: "git:commit-tested", SourceVersion: "commit-tested"}}}
			request.Material.Evidence = []a.SyncEvidenceInput{{LocalKey: "test", ArtifactLocalKey: "build", Evidence: a.RegisterEvidenceCommand{Scope: scope, EvidenceType: d.EvidenceTypeTestResult, Description: "assertion log", SourceRef: d.SourceReference{Provider: "test", ID: "test-run"}, CapturedAt: now, SourceVersion: "commit-tested"}}}
			request.Material.ArtifactLocalKeys = []string{"build"}
			request.Material.EvidenceLocalKeys = []string{"test"}
			if hasCriteria {
				request.Material.CriterionLocalEvidence = []a.SignedLocalCriterionEvidence{{CriterionID: criterion.ID, CriterionRevision: signing.Decimal(criterion.Revision), EvidenceLocalKeys: []string{"test"}}}
			}
			if floor == d.AcceptanceDirect && hasCriteria {
				request.Material.Assessments = []a.SignedAssessmentInput{{CriterionID: criterion.ID, CriterionRevision: signing.Decimal(criterion.Revision), Result: d.AssessmentResultMet, Rationale: "the exact submitted test passed", EvidenceLocalKeys: []string{"test"}}}
			}
			envelope, e := signing.Sign(signing.WorkReturn, request, agentKey.String(), agentPrivate)
			must(e)
			returnCC := cc
			returnCC.CommandID = rid
			returnCC.IdempotencyKey = request.IdempotencyKey

			returned, e := service.ReturnSignedWork(agentCtx, returnCC, a.ReturnSignedWorkCommand{Envelope: envelope})
			must(e)
			delivery := decodeReceipt(t, returned.Value.Receipt, server, pub)
			u, e := store.Begin(ctx)
			must(e)
			review, e := u.(ports.SignedContractUnitOfWork).SignedContracts().Case(ctx, scope, d.ID(delivery.ReviewCaseID))
			must(e)
			must(u.Rollback())
			// Grant review acquisition to the original Principal expressly: rejection must
			// come from independence, not merely a missing permission.
			must(sec.SetGrant(adminCtx, ports.NamespaceGrant{NamespaceID: ns, PrincipalID: identity.PrincipalID, Permissions: []ports.Permission{ports.PermissionStateRead, ports.PermissionWorkContractAcquire, ports.PermissionWorkWrite, ports.PermissionWorkContractReturn, ports.PermissionWorkReviewAcquire, ports.PermissionRecordsWrite}}))
			u, e = store.Begin(ctx)
			must(e)
			reg := u.(ports.SigningIdentityUnitOfWork).SigningIdentity()
			previousVersion := policy.Version
			policy.Version++
			policy.PermittedOperations = append(policy.PermittedOperations, string(ports.PermissionWorkReviewAcquire))
			must(reg.SaveCredentialPolicy(ctx, policy, previousVersion))
			must(u.Commit())
			nextCC := func(id a.Identity, key string) d.CommandContext {
				commandID, e := ids.NewID()
				must(e)
				return d.CommandContext{PrincipalID: id.PrincipalID, Actor: id.Actor, CommandID: commandID, IdempotencyKey: key}
			}
			if _, e = service.AcquireSignedReviewContract(agentCtx, nextCC(identity, "executor-self-review"), a.AcquireSignedReviewContractCommand{Scope: scope, ReviewCaseID: review.ID, ExpectedReviewCaseVersion: review.Version, SignerKeyID: agentKey}); e == nil {
				t.Fatal("execution Principal acquired its own review")
			}
			participant := func(principal string, permissions []ports.Permission) (a.Identity, context.Context, d.ID, ed25519.PrivateKey, d.CredentialPolicy) {
				must(sec.SetGrant(adminCtx, ports.NamespaceGrant{NamespaceID: ns, PrincipalID: principal, Permissions: permissions}))
				cred, token, e := sec.IssueCredential(adminCtx, ns, principal, d.ActorRef{Kind: d.ActorKindAgent, Provider: "test", ID: principal}, now.Add(time.Hour))
				must(e)
				id, e := sec.Authenticate(ctx, token)
				must(e)
				public, private, e := ed25519.GenerateKey(rand.Reader)
				must(e)
				fingerprint, e := signing.Fingerprint(public)
				must(e)
				kid, e := ids.NewID()
				must(e)
				u, e := store.Begin(ctx)
				must(e)
				registry := u.(ports.SigningIdentityUnitOfWork).SigningIdentity()
				must(registry.SaveKey(ctx, d.SigningKey{ID: kid, NamespaceID: ns, PrincipalID: principal, Purpose: "agent", Algorithm: "Ed25519", PublicKey: base64.StdEncoding.EncodeToString(public), Fingerprint: fingerprint, Version: 1, Status: "active", CreatedAt: now, UpdatedAt: now}, 0))
				ops := []string{}
				for _, op := range permissions {
					ops = append(ops, string(op))
				}
				p := d.CredentialPolicy{NamespaceID: ns, CredentialID: cred.ID, PrincipalID: principal, Version: 1, PermittedOperations: ops, AcceptanceFloor: d.AcceptanceIndependentReview, AllowedSigningKeyIDs: []d.ID{kid}, MaxActiveWorkContracts: 3, MaxActiveReviewContracts: 1, UpdatedAt: now}
				must(registry.SaveCredentialPolicy(ctx, p, 0))
				must(u.Commit())
				return id, a.WithIdentity(ctx, id), kid, private, p
			}
			reviewer, reviewCtx, reviewKey, reviewPrivate, reviewPolicy := participant("reviewer", []ports.Permission{ports.PermissionStateRead, ports.PermissionWorkReviewAcquire, ports.PermissionWorkReviewDecide, ports.PermissionRecordsWrite, ports.PermissionAssessmentWrite, ports.PermissionConclusionWrite})
			administrator, interventionCtx, _, _, _ := participant("review-administrator", []ports.Permission{ports.PermissionStateRead, ports.PermissionNamespaceAdmin, ports.PermissionWorkContractRevoke})
			acquiredReview, e := service.AcquireSignedReviewContract(reviewCtx, nextCC(reviewer, "review-round-one-acquisition"), a.AcquireSignedReviewContractCommand{Scope: scope, ReviewCaseID: review.ID, ExpectedReviewCaseVersion: review.Version, SignerKeyID: reviewKey, TTLSeconds: 300})
			must(e)
			// Review takeover changes only execution/fence; no lease extension.
			old := acquiredReview.Value.Contract
			resumed, e := service.ResumeSignedReviewContract(reviewCtx, nextCC(reviewer, "review-resume-one"), a.ResumeSignedReviewContractCommand{Scope: scope, ContractID: old.ID, SignerKeyID: reviewKey, Authority: a.ContractAuthority{ExecutionID: old.ExecutionID, FencingToken: old.FencingToken, SpecDigest: old.Binding.SpecificationDigest}, AuthorityDigest: signing.Digest(acquiredReview.Value.IssuedAuthority.Payload), ExpectedLeaseVersion: old.LeaseVersion})
			must(e)
			if resumed.Value.Contract.ExecutionID == old.ExecutionID || resumed.Value.Contract.FencingToken <= old.FencingToken || !resumed.Value.Contract.ExpiresAt.Equal(old.ExpiresAt) {
				t.Fatal("review takeover failed fencing or extended lease")
			}
			sendReview := func(result a.SignedReviewContractResult, decision, key string, material a.SignedReviewMaterial) (a.MutationResult[a.SignedReturnResult], error) {
				c := result.Contract
				rid, e := ids.NewID()
				must(e)
				payload := signing.ReviewReturnPayload[a.SignedReviewMaterial]{RequestBinding: signing.RequestBinding{Binding: signing.Binding{ProtocolVersion: 2, ServerID: server.ID.String(), NamespaceID: ns.String(), OutcomeID: scope.OutcomeID.String(), PrincipalID: reviewer.PrincipalID, SignerKeyID: reviewKey.String()}, OperationKind: "review_return", RequestID: rid.String(), IdempotencyKey: key, ContractID: c.ID.String(), WorkItemID: c.WorkItemID.String(), ExecutionID: c.ExecutionID.String(), FencingToken: signing.Decimal(c.FencingToken), SpecDigest: c.Binding.SpecificationDigest, AuthorityDigest: signing.Digest(result.IssuedAuthority.Payload), ExpectedContractVersion: signing.Decimal(c.Version), ExpectedLeaseVersion: signing.Decimal(c.LeaseVersion), ExpectedWorkItemVersion: result.WorkItemVersion, PolicyRevision: signing.Decimal(reviewPolicy.Version)}, ExpectedReviewCaseVersion: signing.Decimal(result.Case.Version), ReviewCaseID: c.CaseID.String(), SubmissionID: c.SubmissionID.String(), SubmissionDigest: c.SubmissionDigest, Decision: decision, Material: material}
				signed, e := signing.Sign(signing.ReviewReturn, payload, reviewKey.String(), reviewPrivate)
				must(e)
				return service.ReturnSignedReview(reviewCtx, nextCC(reviewer, key), a.ReturnSignedReviewCommand{Envelope: signed})
			}
			revoked, e := service.RevokeSignedContract(interventionCtx, nextCC(administrator, "administrative-review-revocation"), a.RevokeSignedContractCommand{Scope: scope, ContractKind: "review", ContractID: resumed.Value.Contract.ID, ExpectedContractVersion: resumed.Value.Contract.Version, Reason: "assign a fresh independent review"})
			must(e)
			if revoked.Value.ReviewCase == nil || revoked.Value.ReviewCase.Status != d.ReviewPending {
				t.Fatal("revoking reviewer did not release the case")
			}
			if _, e = sendReview(resumed.Value, "inconclusive", "revoked-review-return", a.SignedReviewMaterial{Reason: "old revoked authority"}); e == nil {
				t.Fatal("revoked reviewer authority returned a new decision")
			}
			reacquired, e := service.AcquireSignedReviewContract(reviewCtx, nextCC(reviewer, "reacquired-after-revocation"), a.AcquireSignedReviewContractCommand{Scope: scope, ReviewCaseID: revoked.Value.ReviewCase.ID, ExpectedReviewCaseVersion: revoked.Value.ReviewCase.Version, SignerKeyID: reviewKey})
			must(e)
			resumed.Value = reacquired.Value
			if _, e = service.InterveneSignedReviewCase(reviewCtx, nextCC(reviewer, "unauthorized-case-cancellation"), a.InterveneSignedReviewCaseCommand{Scope: scope, ReviewCaseID: resumed.Value.Case.ID, ExpectedReviewCaseVersion: resumed.Value.Case.Version, Status: d.ReviewCancelled, Reason: "reviewer cannot grant itself Namespace administration"}); e == nil {
				t.Fatal("reviewer cancelled a case without administration permission")
			}
			if _, e = sendReview(resumed.Value, "approved", "empty-review-approval", a.SignedReviewMaterial{Reason: "approval without assessments"}); e == nil {
				t.Fatal("review approved absent required assessments")
			}
			inconclusive, e := sendReview(resumed.Value, "inconclusive", "review-inconclusive", a.SignedReviewMaterial{Reason: "needs an additional independent check"})
			must(e)
			inconclusiveReceipt := decodeReceipt(t, inconclusive.Value.Receipt, server, pub)
			if inconclusiveReceipt.WorkItemLifecycle != "in_progress" || !inconclusiveReceipt.LocalObligationClosed {
				t.Fatal("inconclusive review completed work or retained local authority")
			}
			u, e = store.Begin(ctx)
			must(e)
			review, e = u.(ports.SignedContractUnitOfWork).SignedContracts().Case(ctx, scope, review.ID)
			must(e)
			if review.Status != d.ReviewPending {
				t.Fatal("inconclusive review did not release the case")
			}
			must(u.Rollback())
			secondReview, e := service.AcquireSignedReviewContract(reviewCtx, nextCC(reviewer, "review-second-acquisition"), a.AcquireSignedReviewContractCommand{Scope: scope, ReviewCaseID: review.ID, ExpectedReviewCaseVersion: review.Version, SignerKeyID: reviewKey})
			must(e)
			findingID, e := ids.NewID()
			must(e)
			finding := d.SignedFinding{ID: findingID, CriterionID: &criterion.ID, Description: "rerun the bounded test against the corrected commit"}
			changes, e := sendReview(secondReview.Value, "changes_requested", "review-changes-requested", a.SignedReviewMaterial{Reason: "test needs correction", Findings: []d.SignedFinding{finding}})
			must(e)
			changesReceipt := decodeReceipt(t, changes.Value.Receipt, server, pub)
			if changesReceipt.Disposition != "changes_requested" || changesReceipt.WorkItemLifecycle != "in_progress" {
				t.Fatal("changes requested incorrectly approved Task")
			}
			must(sec.RevokeCredential(adminCtx, ns, credential.ID))
			executor, executorCtx, executorKey, executorPrivate, executorPolicy := participant("correction-executor", []ports.Permission{ports.PermissionStateRead, ports.PermissionWorkContractAcquire, ports.PermissionWorkWrite, ports.PermissionWorkContractReturn, ports.PermissionRecordsWrite, ports.PermissionWorkReviewAcquire})
			u, e = store.Begin(ctx)
			must(e)
			currentWork, e := u.WorkItems().Get(ctx, scope, work.ID)
			must(e)
			must(u.Rollback())
			if currentWork.PendingReviewCaseID != nil || currentWork.CorrectionReviewCaseID == nil {
				t.Fatal("correction navigation did not replace pending review")
			}
			correction, e := service.AcquireSignedWorkContract(executorCtx, nextCC(executor, "correction-acquisition"), a.AcquireSignedWorkContractCommand{Scope: scope, WorkItemID: work.ID, ExpectedWorkItemVersion: currentWork.Version, SignerKeyID: executorKey, PreviousReviewCaseID: &review.ID})
			must(e)
			correctedContract := correction.Value.Contract
			if correctedContract.FencingToken <= c.FencingToken || correctedContract.ID == c.ID || correctedContract.SignedBinding.PreviousSubmissionID == nil || len(correctedContract.SignedBinding.CorrectionFindings) != 1 {
				t.Fatal("correction did not get a new fenced authority and immutable targets")
			}
			request.RequestID = testID("0199a555-0000-7000-8000-000000000099").String()
			request.IdempotencyKey = "corrected-delivery"
			request.PrincipalID = executor.PrincipalID
			request.SignerKeyID = executorKey.String()
			request.ContractID = correctedContract.ID.String()
			request.ExecutionID = correctedContract.ExecutionID.String()
			request.FencingToken = signing.Decimal(correctedContract.FencingToken)
			request.SpecDigest = correctedContract.SignedBinding.SpecificationDigest
			request.AuthorityDigest = signing.Digest(correction.Value.IssuedAuthority.Payload)
			request.ExpectedContractVersion = signing.Decimal(correctedContract.Version)
			request.ExpectedLeaseVersion = signing.Decimal(correctedContract.LeaseVersion)
			request.ExpectedWorkItemVersion = signing.Decimal(correction.Value.WorkItem.Version)
			request.PolicyRevision = signing.Decimal(executorPolicy.Version)
			request.SupersedesSubmissionID = delivery.SubmissionID
			request.Material.Result.ContractID = correctedContract.ID
			request.Material.Result.SpecDigest = correctedContract.SignedBinding.SpecificationDigest
			request.Material.Result.Summary = "corrected bounded result"
			request.Material.Artifacts[0].Artifact.SourceVersion = "commit-corrected"
			request.Material.Evidence[0].Evidence.SourceVersion = "commit-corrected"
			request.Material.CorrectionResponses = []a.SignedFindingResponse{{FindingID: findingID, Summary: "the test was corrected and rerun", EvidenceLocalKeys: []string{"test"}}}
			correctedEnvelope, e := signing.Sign(signing.WorkReturn, request, executorKey.String(), executorPrivate)
			must(e)
			corrected, e := service.ReturnSignedWork(executorCtx, nextCC(executor, request.IdempotencyKey), a.ReturnSignedWorkCommand{Envelope: correctedEnvelope})
			must(e)
			correctedReceipt := decodeReceipt(t, corrected.Value.Receipt, server, pub)
			u, e = store.Begin(ctx)
			must(e)
			newCase, e := u.(ports.SignedContractUnitOfWork).SignedContracts().Case(ctx, scope, d.ID(correctedReceipt.ReviewCaseID))
			must(e)
			if newCase.Round != 2 || len(newCase.ExecutionPrincipals) != 2 || newCase.ExecutionPrincipals[0] != "executor" || newCase.ExecutionPrincipals[1] != executor.PrincipalID {
				t.Fatal("correction round lost full execution Principal history")
			}
			must(u.Rollback())
			if _, e = service.AcquireSignedReviewContract(executorCtx, nextCC(executor, "correction-self-review"), a.AcquireSignedReviewContractCommand{Scope: scope, ReviewCaseID: newCase.ID, ExpectedReviewCaseVersion: newCase.Version, SignerKeyID: executorKey}); e == nil {
				t.Fatal("correction executor acquired its own review")
			}
			finalReview, e := service.AcquireSignedReviewContract(reviewCtx, nextCC(reviewer, "final-review-acquisition"), a.AcquireSignedReviewContractCommand{Scope: scope, ReviewCaseID: newCase.ID, ExpectedReviewCaseVersion: newCase.Version, SignerKeyID: reviewKey})
			must(e)
			finalEvidence := d.ID(correctedReceipt.LocalKeys["test"])

			approvalMaterial := a.SignedReviewMaterial{Reason: "verified the corrected immutable submission", ReviewedSourceVersion: "commit-corrected", Evidence: []a.SyncEvidenceInput{{LocalKey: "reviewer-check", Evidence: a.RegisterEvidenceCommand{Scope: scope, EvidenceType: d.EvidenceTypeTestResult, Description: "independent reviewer check", SourceRef: d.SourceReference{Provider: "review", ID: "review-test-run"}, CapturedAt: now, SourceVersion: "commit-corrected"}}}, CriterionLocalEvidence: []a.SignedLocalCriterionEvidence{{CriterionID: criterion.ID, CriterionRevision: signing.Decimal(criterion.Revision), EvidenceLocalKeys: []string{"reviewer-check"}}}, Assessments: []a.SignedAssessmentInput{{CriterionID: criterion.ID, CriterionRevision: signing.Decimal(criterion.Revision), Result: d.AssessmentResultMet, Rationale: "exact submitted material plus an independent check passed", EvidenceIDs: []d.ID{finalEvidence}, EvidenceLocalKeys: []string{"reviewer-check"}}}}
			blocker, e := service.CreateBlocker(executorCtx, nextCC(executor, "blocker-during-independent-review"), a.CreateBlockerCommand{Scope: scope, BlockedRef: work.Ref(), ExternalCause: &d.ExternalCause{Provider: "test", ID: "external-hold", Description: "wait for clearance"}, Description: "concurrent operational hold", Propagation: d.BlockerPropagationDirect})
			must(e)
			if _, e = sendReview(finalReview.Value, "approved", "blocked-review-approval-attempt", approvalMaterial); e == nil {
				t.Fatal("review approved despite a live blocker")
			}
			u, e = store.Begin(ctx)
			must(e)
			unchangedCase, e := u.(ports.SignedContractUnitOfWork).SignedContracts().Case(ctx, scope, newCase.ID)
			must(e)
			unchangedAuthority, e := u.(ports.SignedContractUnitOfWork).SignedContracts().ReviewContract(ctx, scope, finalReview.Value.Contract.ID)
			must(e)
			if unchangedCase.Status != d.ReviewInReview || unchangedCase.LatestDecisionID != nil || unchangedAuthority.Status != d.ContractActive {
				t.Fatal("blocked approval partially committed review decision")
			}
			must(u.Rollback())
			_, e = service.ResolveBlocker(executorCtx, nextCC(executor, "resolve-independent-review-blocker"), a.ResolveBlockerCommand{Scope: scope, BlockerID: blocker.Value.ID, ExpectedVersion: blocker.Value.Version, ResolutionSummary: "external hold cleared"})
			must(e)
			approved, e := sendReview(finalReview.Value, "approved", "final-review-approved", approvalMaterial)
			must(e)
			approvedReceipt := decodeReceipt(t, approved.Value.Receipt, server, pub)
			if approvedReceipt.Disposition != "review_approved" || approvedReceipt.WorkItemLifecycle != "done" {
				t.Fatal("independent approval did not complete the Task")
			}
			u, e = store.Begin(ctx)
			must(e)
			done, e := u.WorkItems().Get(ctx, scope, work.ID)
			must(e)
			if done.CurrentConclusion == nil || done.CurrentConclusion.PrincipalID != reviewer.PrincipalID || done.CurrentConclusion.SubmissionID == nil || *done.CurrentConclusion.SubmissionID != d.ID(correctedReceipt.SubmissionID) || done.PendingReviewCaseID != nil {
				t.Fatal("review conclusion did not bind reviewer/exact corrected material")
			}
			original, e := u.(ports.SignedContractUnitOfWork).SignedWorkContracts().Get(ctx, scope, c.ID)
			must(e)
			if original.Status != d.ContractDelivered {
				t.Fatal("approval reactivated/rewrote original executor contract")
			}
			acceptedSubmission, e := u.(ports.SignedContractUnitOfWork).SignedWorkContracts().GetSubmission(ctx, scope, d.ID(correctedReceipt.SubmissionID))
			must(e)
			if len(acceptedSubmission.Material.EvidenceIDs) != 1 || acceptedSubmission.Digest != correctedReceipt.SubmissionDigest || approvedReceipt.LocalKeys["reviewer-check"] == "" {
				t.Fatal("review observations rewrote executor submission or lost receipt linkage")
			}
			must(u.Rollback())
			// Cancellation and supersession close only the review authority. An
			// explicitly acknowledged fresh acquisition can then replan the Task.
			for index, status := range []d.ReviewCaseStatus{d.ReviewCancelled, d.ReviewSuperseded} {
				candidate := works[index+1]
				acquired, e := service.AcquireSignedWorkContract(executorCtx, nextCC(executor, fmt.Sprintf("intervention-execution-%d", index)), a.AcquireSignedWorkContractCommand{Scope: scope, WorkItemID: candidate.ID, ExpectedWorkItemVersion: candidate.Version, SignerKeyID: executorKey})
				must(e)
				contract := acquired.Value.Contract
				intent := request
				rid, e := ids.NewID()
				must(e)
				intent.RequestID = rid.String()
				intent.IdempotencyKey = fmt.Sprintf("intervention-delivery-%d", index)
				intent.ContractID = contract.ID.String()
				intent.WorkItemID = candidate.ID.String()
				intent.ExecutionID = contract.ExecutionID.String()
				intent.FencingToken = signing.Decimal(contract.FencingToken)
				intent.SpecDigest = contract.SignedBinding.SpecificationDigest
				intent.AuthorityDigest = signing.Digest(acquired.Value.IssuedAuthority.Payload)
				intent.ExpectedContractVersion = signing.Decimal(contract.Version)
				intent.ExpectedLeaseVersion = signing.Decimal(contract.LeaseVersion)
				intent.ExpectedWorkItemVersion = signing.Decimal(acquired.Value.WorkItem.Version)
				intent.SupersedesSubmissionID = ""
				intent.Material.Result.ContractID = contract.ID
				intent.Material.Result.WorkItemID = candidate.ID
				intent.Material.Result.SpecDigest = intent.SpecDigest
				intent.Material.CorrectionResponses = nil
				intent.Material.CriterionLocalEvidence = []a.SignedLocalCriterionEvidence{{CriterionID: candidate.Criteria.Items[0].ID, CriterionRevision: signing.Decimal(candidate.Criteria.Items[0].Revision), EvidenceLocalKeys: []string{"test"}}}
				envelope, e := signing.Sign(signing.WorkReturn, intent, executorKey.String(), executorPrivate)
				must(e)
				delivered, e := service.ReturnSignedWork(executorCtx, nextCC(executor, intent.IdempotencyKey), a.ReturnSignedWorkCommand{Envelope: envelope})
				must(e)
				receipt := decodeReceipt(t, delivered.Value.Receipt, server, pub)
				u, e := store.Begin(ctx)
				must(e)
				caseToClose, e := u.(ports.SignedContractUnitOfWork).SignedContracts().Case(ctx, scope, d.ID(receipt.ReviewCaseID))
				must(e)
				must(u.Rollback())
				assigned, e := service.AcquireSignedReviewContract(reviewCtx, nextCC(reviewer, fmt.Sprintf("intervention-review-%d", index)), a.AcquireSignedReviewContractCommand{Scope: scope, ReviewCaseID: caseToClose.ID, ExpectedReviewCaseVersion: caseToClose.Version, SignerKeyID: reviewKey})
				must(e)
				closed, e := service.InterveneSignedReviewCase(interventionCtx, nextCC(administrator, fmt.Sprintf("intervention-case-%d", index)), a.InterveneSignedReviewCaseCommand{Scope: scope, ReviewCaseID: caseToClose.ID, ExpectedReviewCaseVersion: assigned.Value.Case.Version, Status: status, Reason: "authorized material replanning"})
				must(e)
				if closed.Value.ReviewCase.Status != status {
					t.Fatal("case intervention did not persist its explicit disposition")
				}
				u, e = store.Begin(ctx)
				must(e)
				task, e := u.WorkItems().Get(ctx, scope, candidate.ID)
				must(e)
				reviewAuthority, e := u.(ports.SignedContractUnitOfWork).SignedContracts().ReviewContract(ctx, scope, assigned.Value.Contract.ID)
				must(e)
				must(u.Rollback())
				if task.Lifecycle != d.WorkItemLifecycleInProgress || task.PendingReviewCaseID != nil || reviewAuthority.Status != d.ContractRevoked {
					t.Fatal("intervention completed Task or left review authority active")
				}
				command := a.AcquireSignedWorkContractCommand{Scope: scope, WorkItemID: task.ID, ExpectedWorkItemVersion: task.Version, SignerKeyID: executorKey}
				if _, e = service.AcquireSignedWorkContract(executorCtx, nextCC(executor, fmt.Sprintf("unacknowledged-replan-%d", index)), command); e == nil {
					t.Fatal("replanning omitted explicit historical case acknowledgement")
				}
				command.PreviousReviewCaseID = &caseToClose.ID
				replanned, e := service.AcquireSignedWorkContract(executorCtx, nextCC(executor, fmt.Sprintf("acknowledged-replan-%d", index)), command)
				must(e)
				if replanned.Value.Contract.ID == contract.ID || replanned.Value.Contract.FencingToken <= contract.FencingToken || replanned.Value.Contract.SignedBinding.PreviousReviewCaseID == nil {
					t.Fatal("replanning reused old execution or lost the historical target")
				}
			}

		})
	}
}
func decodeReceipt(t *testing.T, document signing.Document, server d.ServerIdentity, public ed25519.PublicKey) signing.ReceiptPayload {
	t.Helper()
	envelope, err := document.Envelope()
	if err != nil {
		t.Fatal(err)
	}
	receipt, _, err := signing.Decode[signing.ReceiptPayload](envelope, signing.AcceptanceReceipt, server.IssuerKeyID.String(), public)
	if err != nil {
		t.Fatal(err)
	}
	return receipt
}
