// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.
package postgres

import (
	"context"
	"crypto/ed25519"
	"encoding/base64"
	a "github.com/A1b3rt0M3rcad0/wos/packages/wos-core/application"
	d "github.com/A1b3rt0M3rcad0/wos/packages/wos-core/domain"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/ports"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/signing"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/storage/memory"
	"path/filepath"
	"testing"
	"time"
)

func TestExplicitSignedCutoverDrainsLegacyAuthorityAndPreservesReceipt(t *testing.T) {
	requirePostgres(t)
	for _, backend := range []string{"memory", "sql"} {
		t.Run(backend, func(t *testing.T) {
			var store interface {
				ports.SecurityStore
				ports.TransactionManager
			}
			if backend == "memory" {
				store = memory.New()
			} else {
				store = openTestStore(t, filepath.Join(t.TempDir(), "signed-cutover.db"))
			}
			ctx := context.Background()
			now := time.Now().UTC()
			clock := sqliteFixedClock{now}
			ids := &sqliteSequenceIDs{prefix: "0199a889", next: 1}
			must := func(e error) {
				t.Helper()
				if e != nil {
					t.Fatal(e)
				}
			}
			ns := testID("0199a888-0000-7000-8000-000000000001")
			scope := d.Scope{NamespaceID: ns, OutcomeID: testID("0199a888-0000-7000-8000-000000000002")}
			security := &a.SecurityService{Store: store, Clock: clock, IDs: ids}
			const token = "signed-cutover-admin-credential-at-least-32"
			must(security.Bootstrap(ctx, ports.Namespace{ID: ns, Name: "cutover"}, "operator", token))
			identity, e := security.Authenticate(ctx, token)
			must(e)
			admin := a.WithIdentity(ctx, identity)
			service, e := a.NewAuthorizedService(store, clock, ids, security)
			must(e)
			u, e := store.Begin(ctx)
			must(e)
			outcome, e := d.NewOutcome(scope.OutcomeID, ns, "explicit cutover", "", "verified", d.PriorityNormal, now)
			must(e)
			outcome.Lifecycle = d.OutcomeLifecycleActive
			must(u.Outcomes().Insert(ctx, outcome))
			work, e := d.NewWorkItem(testID("0199a888-0000-7000-8000-000000000003"), scope, "preserve unsigned history", "", d.PriorityNormal, d.WorkItemLifecycleTodo, now)
			must(e)
			must(u.WorkItems().Insert(ctx, work))
			must(u.Commit())
			cc := func(key string) d.CommandContext {
				id, e := ids.NewID()
				must(e)
				return d.CommandContext{PrincipalID: identity.PrincipalID, Actor: identity.Actor, CommandID: id, IdempotencyKey: "signed-cutover-" + key}
			}
			change := a.SetNamespaceWorkProtocolCommand{Scope: scope, ExpectedProtocolVersion: 1, Phase: d.WorkProtocolDraining, Reason: "retire legacy writers"}
			draining, e := service.SetNamespaceWorkProtocol(admin, cc("drain-legacy"), change)
			must(e)
			change.ExpectedProtocolVersion = draining.Value.Protocol.Version
			change.Phase = d.WorkProtocolContracts
			change.WritersDrained = true
			v1, e := service.SetNamespaceWorkProtocol(admin, cc("activate-v1"), change)
			must(e)
			tx, e := store.Begin(ctx)
			must(e)
			work, e = tx.WorkItems().Get(ctx, scope, work.ID)
			must(e)
			tx.Rollback()
			acquisition := a.AcquireWorkContractCommand{Scope: scope, WorkItemID: work.ID, ExpectedWorkItemVersion: work.Version, TTLSeconds: 300}
			originalCC := cc("v1-original-acquisition")
			acquired, e := service.AcquireWorkContract(admin, originalCC, acquisition)
			must(e)
			change.ExpectedProtocolVersion = v1.Value.Protocol.Version
			change.Phase = d.WorkProtocolSigned
			if _, e = service.SetNamespaceWorkProtocol(admin, cc("skip-signed-drain"), change); e == nil {
				t.Fatal("signed activation skipped drain")
			}
			change.Phase = d.WorkProtocolSignedDraining
			change.WritersDrained = false
			signedDrain, e := service.SetNamespaceWorkProtocol(admin, cc("drain-v1"), change)
			must(e)
			if signedDrain.Value.Protocol.WritersDrained {
				t.Fatal("old operator acknowledgement silently reused")
			}
			if _, e = service.AcquireWorkContract(admin, cc("new-v1-during-drain"), acquisition); e == nil {
				t.Fatal("signed drain granted new unsigned authority")
			}
			change.ExpectedProtocolVersion = signedDrain.Value.Protocol.Version
			change.Phase = d.WorkProtocolSigned
			if _, e = service.SetNamespaceWorkProtocol(admin, cc("without-drain-ack"), change); e == nil {
				t.Fatal("signed activation lacked operator drain")
			}
			change.WritersDrained = true
			if _, e = service.SetNamespaceWorkProtocol(admin, cc("with-active-v1"), change); e == nil {
				t.Fatal("active unsigned authority survived activation")
			}
			revoked, e := service.RevokeWorkContract(admin, cc("revoke-old-authority"), a.RevokeWorkContractCommand{Scope: scope, ContractID: acquired.Value.Contract.ID, ExpectedContractVersion: acquired.Value.Contract.Version, Reason: "explicit operator drain"})
			must(e)
			if _, e = service.SetNamespaceWorkProtocol(admin, cc("without-issuer"), change); e == nil {
				t.Fatal("activation without configured signing host")
			}
			private := ed25519.NewKeyFromSeed(make([]byte, 32))
			public := private.Public().(ed25519.PublicKey)
			server := d.ServerIdentity{ID: testID("0199a888-0000-7000-8000-000000000004"), IssuerKeyID: testID("0199a888-0000-7000-8000-000000000005"), PublicKey: base64.StdEncoding.EncodeToString(public), Fingerprint: signing.Digest(public), CreatedAt: now}
			must(service.ConfigureSignedIssuer(ctx, acquisitionIssuer{server, private}, d.AcceptanceIndependentReview))
			security.ServerID = server.ID.String()
			if _, e = service.SetNamespaceWorkProtocol(admin, cc("without-policy"), change); e == nil {
				t.Fatal("activation without explicit Namespace acceptance policy")
			}
			own, e := security.SigningIdentity(admin, nil)
			must(e)
			_, e = security.SigningMutation(admin, "configure-namespace-floor", a.SigningSecurityIntent{NamespaceID: ns, ExpectedNamespaceVersion: own.NamespaceVersion, Operation: "set_acceptance_policy", AcceptancePolicy: &d.WorkAcceptancePolicy{NamespaceID: ns, AcceptanceFloor: d.AcceptanceIndependentReview, MaxActiveWorkContracts: 3, MaxActiveReviewContracts: 1}})
			must(e)
			readiness, e := service.ReadSignedState(admin, a.SignedStateQuery{Scope: scope, Resource: "protocol_preflight"})
			must(e)
			if readiness.Readiness == nil || !readiness.Readiness.ReadyWithOperatorDrain || readiness.Readiness.ValidUnsignedContracts != 0 {
				t.Fatal("readiness lost drain prerequisites")
			}
			activationCC := cc("activate-signed-v2")
			activated, e := service.SetNamespaceWorkProtocol(admin, activationCC, change)
			must(e)
			if activated.Value.Protocol.WriterEpoch != 2 || !activated.Value.Protocol.WritersDrained {
				t.Fatal("signed activation did not advance writer epoch")
			}
			operation, e := service.ReadSignedState(admin, a.SignedStateQuery{Scope: scope, Resource: "operation", IdempotencyKey: activationCC.IdempotencyKey})
			must(e)
			if operation.OperationCommandID == nil || *operation.OperationCommandID != activated.CommandID || operation.OperationName != "SetNamespaceWorkProtocol" {
				t.Fatal("cutover response not retained by original-CID registry")
			}
			// Preserve exact public response after the short cache is unavailable.
			recoveredService, e := a.NewAuthorizedService(signedNoCacheManager{base: store}, clock, ids, security)
			must(e)
			replayedActivation, e := recoveredService.SetNamespaceWorkProtocol(admin, activationCC, change)
			must(e)
			if !replayedActivation.IdempotentReplay || replayedActivation.CommandID != activated.CommandID || replayedActivation.Value.Protocol.Version != activated.Value.Protocol.Version {
				t.Fatal("cutover recovery activated again or changed original response")
			}
			replay, e := service.AcquireWorkContract(admin, originalCC, acquisition)
			must(e)
			if !replay.IdempotentReplay || replay.Value.Contract.ID != acquired.Value.Contract.ID {
				t.Fatal("cutover rewrote original unsigned receipt")
			}
			if _, e = service.AcquireWorkContract(admin, cc("new-unsigned-after-v2"), acquisition); e == nil {
				t.Fatal("new unsigned mutation bypassed epoch two")
			}
			history, e := service.GetWorkContract(admin, scope, acquired.Value.Contract.ID)
			must(e)
			if history.Value.Contract.Status != d.ContractRevoked || history.Value.Contract.Version != revoked.Value.Contract.Version || history.Value.Contract.SignedBinding != nil {
				t.Fatal("unsigned history was rewritten or signed")
			}
			change.ExpectedProtocolVersion = activated.Value.Protocol.Version
			change.Phase = d.WorkProtocolContracts
			if _, e = service.SetNamespaceWorkProtocol(admin, cc("downgrade-after-v2"), change); e == nil {
				t.Fatal("epoch two was downgraded")
			}
		})
	}
}
