// Code generated by tools/postgresgen/generate.py; DO NOT EDIT.
package postgres

import (
	"context"
	"database/sql"
	"encoding/json"
	d "github.com/A1b3rt0M3rcad0/wos/packages/wos-core/domain"
	"github.com/A1b3rt0M3rcad0/wos/packages/wos-core/ports"
	"reflect"
	"strconv"
	"time"
)

type workContractRepository struct{ uow *unitOfWork }

func (u *unitOfWork) WorkContracts() ports.WorkContractRepository { return workContractRepository{u} }
func (r workContractRepository) Get(ctx context.Context, scope d.Scope, id d.ID) (d.WorkContract, error) {
	var state, spec string
	err := r.uow.tx.QueryRowContext(ctx, `SELECT state_json,spec_json FROM work_contracts WHERE namespace_id=$1 AND outcome_id=$2 AND id=$3`, scope.NamespaceID.String(), scope.OutcomeID.String(), id.String()).Scan(&state, &spec)
	if err != nil {
		return d.WorkContract{}, mapSQLError("get contract", err)
	}
	var c d.WorkContract
	if err := json.Unmarshal([]byte(state), &c); err != nil {
		return c, err
	}
	if err := json.Unmarshal([]byte(spec), &c.Spec); err != nil {
		return c, err
	}
	if c.Scope != scope || c.ID != id {
		return c, d.NewError(d.ErrorCodeInvalidScope, "persisted contract binding mismatch")
	}
	return c, c.Validate()
}
func (r workContractRepository) Current(ctx context.Context, scope d.Scope, work d.ID) (*d.WorkContract, error) {
	var id string
	err := r.uow.tx.QueryRowContext(ctx, `SELECT id FROM work_contracts WHERE namespace_id=$1 AND outcome_id=$2 AND work_item_id=$3 AND status='active'`, scope.NamespaceID.String(), scope.OutcomeID.String(), work.String()).Scan(&id)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, mapSQLError("get current contract", err)
	}
	parsed, err := d.ParseID(id)
	if err != nil {
		return nil, err
	}
	c, err := r.Get(ctx, scope, parsed)
	return &c, err
}
func (r workContractRepository) List(ctx context.Context, scope d.Scope, f ports.ContractFilter) ([]d.WorkContract, error) {
	if f.Limit < 1 || f.Limit > 101 {
		return nil, d.NewError(d.ErrorCodeInvalidArgument, "contract limit outside 1..101")
	}
	rows, err := r.uow.tx.QueryContext(ctx, `SELECT state_json,spec_json FROM work_contracts WHERE namespace_id=$1 AND outcome_id=$2 AND ($3='' OR work_item_id=$4) AND ($5='' OR holder_principal_id=$6) AND ($7='' OR status=$8) AND id>$9 ORDER BY id LIMIT $10`, scope.NamespaceID.String(), scope.OutcomeID.String(), f.WorkItemID.String(), f.WorkItemID.String(), f.HolderPrincipalID, f.HolderPrincipalID, string(f.Status), string(f.Status), f.After.String(), f.Limit)
	if err != nil {
		return nil, mapSQLError("list contracts", err)
	}
	defer rows.Close()
	out := []d.WorkContract{}
	for rows.Next() {
		var state, spec string
		if err := rows.Scan(&state, &spec); err != nil {
			return nil, err
		}
		var c d.WorkContract
		if err := json.Unmarshal([]byte(state), &c); err != nil {
			return nil, err
		}
		if err := json.Unmarshal([]byte(spec), &c.Spec); err != nil {
			return nil, err
		}
		if err := c.Validate(); err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}
func contractState(c d.WorkContract) (string, error) {
	c.Spec = d.WorkContractSpec{}
	return marshalJSON(c)
}
func (r workContractRepository) Insert(ctx context.Context, c d.WorkContract) error {
	if err := c.Validate(); err != nil {
		return err
	}
	if err := ensurePrincipal(ctx, r.uow.tx, c.HolderPrincipalID); err != nil {
		return err
	}
	state, err := contractState(c)
	if err != nil {
		return err
	}
	spec, err := marshalJSON(c.Spec)
	if err != nil {
		return err
	}
	_, err = r.uow.tx.ExecContext(ctx, `INSERT INTO work_contracts (id,namespace_id,outcome_id,work_item_id,holder_principal_id,status,version,lease_version,fencing_token,expires_at,state_json,spec_json,spec_digest) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`, c.ID.String(), c.Scope.NamespaceID.String(), c.Scope.OutcomeID.String(), c.WorkItemID.String(), c.HolderPrincipalID, string(c.Status), int64(c.Version), int64(c.LeaseVersion), strconv.FormatUint(uint64(c.FencingToken), 10), encodeTime(c.ExpiresAt), state, spec, c.SpecDigest)
	return mapSQLError("insert contract", err)
}
func (r workContractRepository) Save(ctx context.Context, c d.WorkContract, version, lease d.Version) error {
	old, err := r.Get(ctx, c.Scope, c.ID)
	if err != nil {
		return err
	}
	if old.Version != version || old.LeaseVersion != lease {
		return d.NewError(d.ErrorCodeVersionConflict, "contract CAS conflict")
	}
	if err := d.ValidateContractUpdate(old, c); err != nil {
		return err
	}
	state, err := contractState(c)
	if err != nil {
		return err
	}
	result, err := r.uow.tx.ExecContext(ctx, `UPDATE work_contracts SET status=$1,version=$2,lease_version=$3,fencing_token=$4,expires_at=$5,state_json=$6 WHERE namespace_id=$7 AND outcome_id=$8 AND id=$9 AND version=$10 AND lease_version=$11`, string(c.Status), int64(c.Version), int64(c.LeaseVersion), strconv.FormatUint(uint64(c.FencingToken), 10), encodeTime(c.ExpiresAt), state, c.Scope.NamespaceID.String(), c.Scope.OutcomeID.String(), c.ID.String(), int64(version), int64(lease))
	if err != nil {
		return mapSQLError("save contract", err)
	}
	n, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if n != 1 {
		return d.NewError(d.ErrorCodeVersionConflict, "contract CAS conflict")
	}
	return nil
}
func (r workContractRepository) InsertCheckpoint(ctx context.Context, p d.WorkCheckpoint) error {
	if err := p.Validate(); err != nil {
		return err
	}
	c, err := r.Get(ctx, p.Scope, p.ContractID)
	if err != nil {
		return err
	}
	if c.WorkItemID != p.WorkItemID {
		return d.NewError(d.ErrorCodeInvalidScope, "checkpoint task mismatch")
	}
	raw, err := marshalJSON(p)
	if err != nil {
		return err
	}
	_, err = r.uow.tx.ExecContext(ctx, `INSERT INTO work_contract_checkpoints (id,namespace_id,outcome_id,contract_id,work_item_id,sequence,payload_json) VALUES ($1,$2,$3,$4,$5,$6,$7)`, p.ID.String(), p.Scope.NamespaceID.String(), p.Scope.OutcomeID.String(), p.ContractID.String(), p.WorkItemID.String(), int64(p.Sequence), raw)
	return mapSQLError("insert checkpoint", err)
}
func (r workContractRepository) ListCheckpoints(ctx context.Context, scope d.Scope, contract, after d.ID, limit int) ([]d.WorkCheckpoint, error) {
	if _, err := r.Get(ctx, scope, contract); err != nil {
		return nil, err
	}
	if limit < 1 || limit > 101 {
		return nil, d.NewError(d.ErrorCodeInvalidArgument, "checkpoint limit outside 1..101")
	}
	rows, err := r.uow.tx.QueryContext(ctx, `SELECT payload_json FROM work_contract_checkpoints WHERE namespace_id=$1 AND outcome_id=$2 AND contract_id=$3 AND id>$4 ORDER BY id LIMIT $5`, scope.NamespaceID.String(), scope.OutcomeID.String(), contract.String(), after.String(), limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []d.WorkCheckpoint{}
	for rows.Next() {
		var raw string
		if err := rows.Scan(&raw); err != nil {
			return nil, err
		}
		var v d.WorkCheckpoint
		if err := json.Unmarshal([]byte(raw), &v); err != nil {
			return nil, err
		}
		if err := v.Validate(); err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}
func (r workContractRepository) InsertSubmission(ctx context.Context, p d.WorkSubmission) error {
	if err := p.Validate(); err != nil {
		return err
	}
	c, err := r.Get(ctx, p.Scope, p.Material.ContractID)
	if err != nil {
		return err
	}
	if c.WorkItemID != p.Material.WorkItemID {
		return d.NewError(d.ErrorCodeInvalidScope, "submission task mismatch")
	}
	// Duplicate identity cannot rewrite immutable material.
	if old, err := r.GetSubmission(ctx, p.Scope, p.ID); err == nil {
		if reflect.DeepEqual(old, p) {
			return nil
		}
		return d.NewError(d.ErrorCodeAlreadyExists, "submission is immutable")
	} else if code, _ := d.ErrorCodeOf(err); code != d.ErrorCodeNotFound {
		return err
	}
	raw, err := marshalJSON(p)
	if err != nil {
		return err
	}
	_, err = r.uow.tx.ExecContext(ctx, `INSERT INTO work_contract_submissions (id,namespace_id,outcome_id,contract_id,work_item_id,submission_digest,payload_json) VALUES ($1,$2,$3,$4,$5,$6,$7)`, p.ID.String(), p.Scope.NamespaceID.String(), p.Scope.OutcomeID.String(), p.Material.ContractID.String(), p.Material.WorkItemID.String(), p.Digest, raw)
	return mapSQLError("insert submission", err)
}
func (r workContractRepository) GetSubmission(ctx context.Context, scope d.Scope, id d.ID) (d.WorkSubmission, error) {
	var raw string
	err := r.uow.tx.QueryRowContext(ctx, `SELECT payload_json FROM work_contract_submissions WHERE namespace_id=$1 AND outcome_id=$2 AND id=$3`, scope.NamespaceID.String(), scope.OutcomeID.String(), id.String()).Scan(&raw)
	if err != nil {
		return d.WorkSubmission{}, mapSQLError("get submission", err)
	}
	var v d.WorkSubmission
	if err := json.Unmarshal([]byte(raw), &v); err != nil {
		return v, err
	}
	if v.ID != id || v.Scope != scope {
		return v, d.NewError(d.ErrorCodeInvalidScope, "submission binding mismatch")
	}
	return v, v.Validate()
}
func (r workContractRepository) ListSubmissions(ctx context.Context, scope d.Scope, contract, after d.ID, limit int) ([]d.WorkSubmission, error) {
	if _, err := r.Get(ctx, scope, contract); err != nil {
		return nil, err
	}
	if limit < 1 || limit > 101 {
		return nil, d.NewError(d.ErrorCodeInvalidArgument, "submission limit outside 1..101")
	}
	rows, err := r.uow.tx.QueryContext(ctx, `SELECT payload_json FROM work_contract_submissions WHERE namespace_id=$1 AND outcome_id=$2 AND contract_id=$3 AND id>$4 ORDER BY id LIMIT $5`, scope.NamespaceID.String(), scope.OutcomeID.String(), contract.String(), after.String(), limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []d.WorkSubmission{}
	for rows.Next() {
		var raw string
		if err := rows.Scan(&raw); err != nil {
			return nil, err
		}
		var v d.WorkSubmission
		if err := json.Unmarshal([]byte(raw), &v); err != nil {
			return nil, err
		}
		if err := v.Validate(); err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, rows.Err()
}

func (r workItemRepository) ContractCandidates(ctx context.Context, scope d.Scope, q ports.ContractCandidateQuery) ([]ports.ContractCandidate, error) {
	if q.Limit < 1 || q.Limit > 101 {
		return nil, d.NewError(d.ErrorCodeInvalidArgument, "candidate limit outside 1..101")
	}
	rows, err := r.uow.tx.QueryContext(ctx, `SELECT id,version,priority,created_at FROM work_items WHERE namespace_id=$1 AND outcome_id=$2 AND contracts_enabled=1 AND lifecycle IN ('todo','in_progress') AND ($3='' OR (CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'normal' THEN 2 ELSE 3 END)>$4 OR ((CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'normal' THEN 2 ELSE 3 END)=$5 AND (created_at>$6 OR (created_at=$7 AND id>$8)))) ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'normal' THEN 2 ELSE 3 END,created_at,id LIMIT $9`, scope.NamespaceID.String(), scope.OutcomeID.String(), q.AfterID.String(), q.AfterPriority, q.AfterPriority, encodeTime(q.AfterCreated), encodeTime(q.AfterCreated), q.AfterID.String(), q.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []ports.ContractCandidate{}
	for rows.Next() {
		var raw string
		var v ports.ContractCandidate
		var created int64
		if err := rows.Scan(&raw, &v.Version, &v.Priority, &created); err != nil {
			return nil, err
		}
		id, err := d.ParseID(raw)
		if err != nil {
			return nil, err
		}
		v.ID = id
		v.CreatedAt = decodeTime(created)
		out = append(out, v)
	}
	return out, rows.Err()
}

func (r idempotencyStore) LookupReceipt(ctx context.Context, ns d.ID, principal string, command d.ID) (d.StoredCommandResult, error) {
	var response string
	var revision int64
	err := r.uow.tx.QueryRowContext(ctx, `SELECT response_json,outcome_revision FROM idempotency_records WHERE namespace_id=$1 AND principal_id=$2 AND command_id=$3 AND status='completed' AND expires_at>$4`, ns.String(), principal, command.String(), encodeTime(time.Now().UTC())).Scan(&response, &revision)
	if err != nil {
		return d.StoredCommandResult{}, mapSQLError("get receipt", err)
	}
	return d.StoredCommandResult{CommandID: command, OutcomeRevision: d.OutcomeRevision(revision), ResponseJSON: json.RawMessage(response)}, nil
}

func (r workContractRepository) GetCheckpoint(ctx context.Context, scope d.Scope, id d.ID) (d.WorkCheckpoint, error) {
	var raw string
	err := r.uow.tx.QueryRowContext(ctx, `SELECT payload_json FROM work_contract_checkpoints WHERE namespace_id=$1 AND outcome_id=$2 AND id=$3`, scope.NamespaceID.String(), scope.OutcomeID.String(), id.String()).Scan(&raw)
	if err != nil {
		return d.WorkCheckpoint{}, mapSQLError("get checkpoint", err)
	}
	var v d.WorkCheckpoint
	if err := json.Unmarshal([]byte(raw), &v); err != nil {
		return v, err
	}
	if v.ID != id || v.Scope != scope {
		return v, d.NewError(d.ErrorCodeInvalidScope, "checkpoint binding mismatch")
	}
	return v, v.Validate()
}
